-- +goose Up
-- +goose StatementBegin
INSERT INTO "country" VALUES ('AF', 'Afghanistan');
INSERT INTO "country" VALUES ('AX', 'Åland Islands');
INSERT INTO "country" VALUES ('AL', 'Albania');
INSERT INTO "country" VALUES ('DZ', 'Algeria');
INSERT INTO "country" VALUES ('AS', 'American Samoa');
INSERT INTO "country" VALUES ('AD', 'Andorra');
INSERT INTO "country" VALUES ('AO', 'Angola');
INSERT INTO "country" VALUES ('AI', 'Anguilla');
INSERT INTO "country" VALUES ('AQ', 'Antarctica');
INSERT INTO "country" VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO "country" VALUES ('AR', 'Argentina');
INSERT INTO "country" VALUES ('AM', 'Armenia');
INSERT INTO "country" VALUES ('AW', 'Aruba');
INSERT INTO "country" VALUES ('AU', 'Australia');
INSERT INTO "country" VALUES ('AT', 'Austria');
INSERT INTO "country" VALUES ('AZ', 'Azerbaijan');
INSERT INTO "country" VALUES ('BS', 'Bahamas');
INSERT INTO "country" VALUES ('BH', 'Bahrain');
INSERT INTO "country" VALUES ('BD', 'Bangladesh');
INSERT INTO "country" VALUES ('BB', 'Barbados');
INSERT INTO "country" VALUES ('BY', 'Belarus');
INSERT INTO "country" VALUES ('BE', 'Belgium');
INSERT INTO "country" VALUES ('BZ', 'Belize');
INSERT INTO "country" VALUES ('BJ', 'Benin');
INSERT INTO "country" VALUES ('BM', 'Bermuda');
INSERT INTO "country" VALUES ('BT', 'Bhutan');
INSERT INTO "country" VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT INTO "country" VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO "country" VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO "country" VALUES ('BW', 'Botswana');
INSERT INTO "country" VALUES ('BV', 'Bouvet Island');
INSERT INTO "country" VALUES ('BR', 'Brazil');
INSERT INTO "country" VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO "country" VALUES ('BN', 'Brunei Darussalam');
INSERT INTO "country" VALUES ('BG', 'Bulgaria');
INSERT INTO "country" VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" VALUES ('BI', 'Burundi');
INSERT INTO "country" VALUES ('KH', 'Cambodia');
INSERT INTO "country" VALUES ('CM', 'Cameroon');
INSERT INTO "country" VALUES ('CA', 'Canada');
INSERT INTO "country" VALUES ('CV', 'Cape Verde');
INSERT INTO "country" VALUES ('KY', 'Cayman Islands');
INSERT INTO "country" VALUES ('CF', 'Central African Republic');
INSERT INTO "country" VALUES ('TD', 'Chad');
INSERT INTO "country" VALUES ('CL', 'Chile');
INSERT INTO "country" VALUES ('CN', 'China');
INSERT INTO "country" VALUES ('CX', 'Christmas Island');
INSERT INTO "country" VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO "country" VALUES ('CO', 'Colombia');
INSERT INTO "country" VALUES ('KM', 'Comoros');
INSERT INTO "country" VALUES ('CG', 'Congo');
INSERT INTO "country" VALUES ('CD', 'Congo, the Democratic Republic of the');
INSERT INTO "country" VALUES ('CK', 'Cook Islands');
INSERT INTO "country" VALUES ('CR', 'Costa Rica');
INSERT INTO "country" VALUES ('CI', 'Côte d''Ivoire');
INSERT INTO "country" VALUES ('HR', 'Croatia');
INSERT INTO "country" VALUES ('CU', 'Cuba');
INSERT INTO "country" VALUES ('CW', 'Curaçao');
INSERT INTO "country" VALUES ('CY', 'Cyprus');
INSERT INTO "country" VALUES ('CZ', 'Czech Republic');
INSERT INTO "country" VALUES ('DK', 'Denmark');
INSERT INTO "country" VALUES ('DJ', 'Djibouti');
INSERT INTO "country" VALUES ('DM', 'Dominica');
INSERT INTO "country" VALUES ('DO', 'Dominican Republic');
INSERT INTO "country" VALUES ('EC', 'Ecuador');
INSERT INTO "country" VALUES ('EG', 'Egypt');
INSERT INTO "country" VALUES ('SV', 'El Salvador');
INSERT INTO "country" VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO "country" VALUES ('ER', 'Eritrea');
INSERT INTO "country" VALUES ('EE', 'Estonia');
INSERT INTO "country" VALUES ('ET', 'Ethiopia');
INSERT INTO "country" VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO "country" VALUES ('FO', 'Faroe Islands');
INSERT INTO "country" VALUES ('FJ', 'Fiji');
INSERT INTO "country" VALUES ('FI', 'Finland');
INSERT INTO "country" VALUES ('FR', 'France');
INSERT INTO "country" VALUES ('GF', 'French Guiana');
INSERT INTO "country" VALUES ('PF', 'French Polynesia');
INSERT INTO "country" VALUES ('TF', 'French Southern Territories');
INSERT INTO "country" VALUES ('GA', 'Gabon');
INSERT INTO "country" VALUES ('GM', 'Gambia');
INSERT INTO "country" VALUES ('GE', 'Georgia');
INSERT INTO "country" VALUES ('DE', 'Germany');
INSERT INTO "country" VALUES ('GH', 'Ghana');
INSERT INTO "country" VALUES ('GI', 'Gibraltar');
INSERT INTO "country" VALUES ('GR', 'Greece');
INSERT INTO "country" VALUES ('GL', 'Greenland');
INSERT INTO "country" VALUES ('GD', 'Grenada');
INSERT INTO "country" VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" VALUES ('GU', 'Guam');
INSERT INTO "country" VALUES ('GT', 'Guatemala');
INSERT INTO "country" VALUES ('GG', 'Guernsey');
INSERT INTO "country" VALUES ('GN', 'Guinea');
INSERT INTO "country" VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "country" VALUES ('GY', 'Guyana');
INSERT INTO "country" VALUES ('HT', 'Haiti');
INSERT INTO "country" VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO "country" VALUES ('VA', 'Holy See (Vatican City State)');
INSERT INTO "country" VALUES ('HN', 'Honduras');
INSERT INTO "country" VALUES ('HK', 'Hong Kong');
INSERT INTO "country" VALUES ('HU', 'Hungary');
INSERT INTO "country" VALUES ('IS', 'Iceland');
INSERT INTO "country" VALUES ('IN', 'India');
INSERT INTO "country" VALUES ('ID', 'Indonesia');
INSERT INTO "country" VALUES ('IR', 'Iran, Islamic Republic of');
INSERT INTO "country" VALUES ('IQ', 'Iraq');
INSERT INTO "country" VALUES ('IE', 'Ireland');
INSERT INTO "country" VALUES ('IM', 'Isle of Man');
INSERT INTO "country" VALUES ('IL', 'Israel');
INSERT INTO "country" VALUES ('IT', 'Italy');
INSERT INTO "country" VALUES ('JM', 'Jamaica');
INSERT INTO "country" VALUES ('JP', 'Japan');
INSERT INTO "country" VALUES ('JE', 'Jersey');
INSERT INTO "country" VALUES ('JO', 'Jordan');
INSERT INTO "country" VALUES ('KZ', 'Kazakhstan');
INSERT INTO "country" VALUES ('KE', 'Kenya');
INSERT INTO "country" VALUES ('KI', 'Kiribati');
INSERT INTO "country" VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO "country" VALUES ('KR', 'Korea, Republic of');
INSERT INTO "country" VALUES ('KW', 'Kuwait');
INSERT INTO "country" VALUES ('KG', 'Kyrgyzstan');
INSERT INTO "country" VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO "country" VALUES ('LV', 'Latvia');
INSERT INTO "country" VALUES ('LB', 'Lebanon');
INSERT INTO "country" VALUES ('LS', 'Lesotho');
INSERT INTO "country" VALUES ('LR', 'Liberia');
INSERT INTO "country" VALUES ('LY', 'Libya');
INSERT INTO "country" VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" VALUES ('LT', 'Lithuania');
INSERT INTO "country" VALUES ('LU', 'Luxembourg');
INSERT INTO "country" VALUES ('MO', 'Macao');
INSERT INTO "country" VALUES ('MK', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO "country" VALUES ('MG', 'Madagascar');
INSERT INTO "country" VALUES ('MW', 'Malawi');
INSERT INTO "country" VALUES ('MY', 'Malaysia');
INSERT INTO "country" VALUES ('MV', 'Maldives');
INSERT INTO "country" VALUES ('ML', 'Mali');
INSERT INTO "country" VALUES ('MT', 'Malta');
INSERT INTO "country" VALUES ('MH', 'Marshall Islands');
INSERT INTO "country" VALUES ('MQ', 'Martinique');
INSERT INTO "country" VALUES ('MR', 'Mauritania');
INSERT INTO "country" VALUES ('MU', 'Mauritius');
INSERT INTO "country" VALUES ('YT', 'Mayotte');
INSERT INTO "country" VALUES ('MX', 'Mexico');
INSERT INTO "country" VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO "country" VALUES ('MD', 'Moldova, Republic of');
INSERT INTO "country" VALUES ('MC', 'Monaco');
INSERT INTO "country" VALUES ('MN', 'Mongolia');
INSERT INTO "country" VALUES ('ME', 'Montenegro');
INSERT INTO "country" VALUES ('MS', 'Montserrat');
INSERT INTO "country" VALUES ('MA', 'Morocco');
INSERT INTO "country" VALUES ('MZ', 'Mozambique');
INSERT INTO "country" VALUES ('MM', 'Myanmar');
INSERT INTO "country" VALUES ('NA', 'Namibia');
INSERT INTO "country" VALUES ('NR', 'Nauru');
INSERT INTO "country" VALUES ('NP', 'Nepal');
INSERT INTO "country" VALUES ('NL', 'Netherlands');
INSERT INTO "country" VALUES ('NC', 'New Caledonia');
INSERT INTO "country" VALUES ('NZ', 'New Zealand');
INSERT INTO "country" VALUES ('NI', 'Nicaragua');
INSERT INTO "country" VALUES ('NE', 'Niger');
INSERT INTO "country" VALUES ('NG', 'Nigeria');
INSERT INTO "country" VALUES ('NU', 'Niue');
INSERT INTO "country" VALUES ('NF', 'Norfolk Island');
INSERT INTO "country" VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO "country" VALUES ('NO', 'Norway');
INSERT INTO "country" VALUES ('OM', 'Oman');
INSERT INTO "country" VALUES ('PK', 'Pakistan');
INSERT INTO "country" VALUES ('PW', 'Palau');
INSERT INTO "country" VALUES ('PS', 'Palestine, State of');
INSERT INTO "country" VALUES ('PA', 'Panama');
INSERT INTO "country" VALUES ('PG', 'Papua New Guinea');
INSERT INTO "country" VALUES ('PY', 'Paraguay');
INSERT INTO "country" VALUES ('PE', 'Peru');
INSERT INTO "country" VALUES ('PH', 'Philippines');
INSERT INTO "country" VALUES ('PN', 'Pitcairn');
INSERT INTO "country" VALUES ('PL', 'Poland');
INSERT INTO "country" VALUES ('PT', 'Portugal');
INSERT INTO "country" VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" VALUES ('QA', 'Qatar');
INSERT INTO "country" VALUES ('RE', 'Réunion');
INSERT INTO "country" VALUES ('RO', 'Romania');
INSERT INTO "country" VALUES ('RU', 'Russian Federation');
INSERT INTO "country" VALUES ('RW', 'Rwanda');
INSERT INTO "country" VALUES ('BL', 'Saint Barthélemy');
INSERT INTO "country" VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO "country" VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO "country" VALUES ('LC', 'Saint Lucia');
INSERT INTO "country" VALUES ('MF', 'Saint Martin (French part)');
INSERT INTO "country" VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO "country" VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO "country" VALUES ('WS', 'Samoa');
INSERT INTO "country" VALUES ('SM', 'San Marino');
INSERT INTO "country" VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO "country" VALUES ('SA', 'Saudi Arabia');
INSERT INTO "country" VALUES ('SN', 'Senegal');
INSERT INTO "country" VALUES ('RS', 'Serbia');
INSERT INTO "country" VALUES ('SC', 'Seychelles');
INSERT INTO "country" VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" VALUES ('SG', 'Singapore');
INSERT INTO "country" VALUES ('SX', 'Sint Maarten (Dutch part)');
INSERT INTO "country" VALUES ('SK', 'Slovakia');
INSERT INTO "country" VALUES ('SI', 'Slovenia');
INSERT INTO "country" VALUES ('SB', 'Solomon Islands');
INSERT INTO "country" VALUES ('SO', 'Somalia');
INSERT INTO "country" VALUES ('ZA', 'South Africa');
INSERT INTO "country" VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO "country" VALUES ('SS', 'South Sudan');
INSERT INTO "country" VALUES ('ES', 'Spain');
INSERT INTO "country" VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" VALUES ('SD', 'Sudan');
INSERT INTO "country" VALUES ('SR', 'Suriname');
INSERT INTO "country" VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO "country" VALUES ('SZ', 'Swaziland');
INSERT INTO "country" VALUES ('SE', 'Sweden');
INSERT INTO "country" VALUES ('CH', 'Switzerland');
INSERT INTO "country" VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO "country" VALUES ('TW', 'Taiwan, Province of China');
INSERT INTO "country" VALUES ('TJ', 'Tajikistan');
INSERT INTO "country" VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO "country" VALUES ('TH', 'Thailand');
INSERT INTO "country" VALUES ('TL', 'Timor-Leste');
INSERT INTO "country" VALUES ('TG', 'Togo');
INSERT INTO "country" VALUES ('TK', 'Tokelau');
INSERT INTO "country" VALUES ('TO', 'Tonga');
INSERT INTO "country" VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO "country" VALUES ('TN', 'Tunisia');
INSERT INTO "country" VALUES ('TR', 'Turkey');
INSERT INTO "country" VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO "country" VALUES ('TV', 'Tuvalu');
INSERT INTO "country" VALUES ('UG', 'Uganda');
INSERT INTO "country" VALUES ('UA', 'Ukraine');
INSERT INTO "country" VALUES ('AE', 'United Arab Emirates');
INSERT INTO "country" VALUES ('GB', 'United Kingdom');
INSERT INTO "country" VALUES ('US', 'United States');
INSERT INTO "country" VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO "country" VALUES ('UY', 'Uruguay');
INSERT INTO "country" VALUES ('UZ', 'Uzbekistan');
INSERT INTO "country" VALUES ('VU', 'Vanuatu');
INSERT INTO "country" VALUES ('VE', 'Venezuela, Bolivarian Republic of');
INSERT INTO "country" VALUES ('VN', 'Viet Nam');
INSERT INTO "country" VALUES ('VG', 'Virgin Islands, British');
INSERT INTO "country" VALUES ('VI', 'Virgin Islands, U.S.');
INSERT INTO "country" VALUES ('WF', 'Wallis and Futuna');
INSERT INTO "country" VALUES ('EH', 'Western Sahara');
INSERT INTO "country" VALUES ('YE', 'Yemen');
INSERT INTO "country" VALUES ('ZM', 'Zambia');
INSERT INTO "country" VALUES ('ZW', 'Zimbabwe');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
TRUNCATE "country" RESTART IDENTITY CASCADE;
-- +goose StatementEnd
