// Code generated by protoc-gen-go. DO NOT EDIT.
// source: key.proto

package key

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/werbot/werbot/pkg/utils/protoutils/ghoster/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_unspecified KeyType = 0
	KeyType_ed25519     KeyType = 1
	KeyType_ecdsa       KeyType = 2
	KeyType_rsa         KeyType = 3
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "unspecified",
		1: "ed25519",
		2: "ecdsa",
		3: "rsa",
	}
	KeyType_value = map[string]int32{
		"unspecified": 0,
		"ed25519":     1,
		"ecdsa":       2,
		"rsa":         3,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_key_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_key_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{0}
}

type SchemeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        string                 `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private       string                 `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	Passphrase    string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	FingerPrint   string                 `protobuf:"bytes,4,opt,name=finger_print,json=fingerPrint,proto3" json:"finger_print,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemeKey) Reset() {
	*x = SchemeKey{}
	mi := &file_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeKey) ProtoMessage() {}

func (x *SchemeKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeKey.ProtoReflect.Descriptor instead.
func (*SchemeKey) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{0}
}

func (x *SchemeKey) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *SchemeKey) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

func (x *SchemeKey) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *SchemeKey) GetFingerPrint() string {
	if x != nil {
		return x.FingerPrint
	}
	return ""
}

// rpc Keys
type Keys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys) Reset() {
	*x = Keys{}
	mi := &file_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{1}
}

// rpc Key
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{2}
}

// rpc AddKey
type AddKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKey) Reset() {
	*x = AddKey{}
	mi := &file_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKey) ProtoMessage() {}

func (x *AddKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKey.ProtoReflect.Descriptor instead.
func (*AddKey) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{3}
}

// rpc UpdateKey
type UpdateKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKey) Reset() {
	*x = UpdateKey{}
	mi := &file_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKey) ProtoMessage() {}

func (x *UpdateKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKey.ProtoReflect.Descriptor instead.
func (*UpdateKey) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{4}
}

// rpc DeleteKey
type DeleteKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKey) Reset() {
	*x = DeleteKey{}
	mi := &file_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey) ProtoMessage() {}

func (x *DeleteKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey.ProtoReflect.Descriptor instead.
func (*DeleteKey) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{5}
}

// rpc GenerateSSHKey
type GenerateSSHKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSSHKey) Reset() {
	*x = GenerateSSHKey{}
	mi := &file_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSSHKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSSHKey) ProtoMessage() {}

func (x *GenerateSSHKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSSHKey.ProtoReflect.Descriptor instead.
func (*GenerateSSHKey) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{6}
}

type Keys_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`       
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"-"`  
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys_Request) Reset() {
	*x = Keys_Request{}
	mi := &file_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys_Request) ProtoMessage() {}

func (x *Keys_Request) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys_Request.ProtoReflect.Descriptor instead.
func (*Keys_Request) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Keys_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Keys_Request) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Keys_Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Keys_Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Keys_Request) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type Keys_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PublicKeys    []*Key_Response        `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys_Response) Reset() {
	*x = Keys_Response{}
	mi := &file_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys_Response) ProtoMessage() {}

func (x *Keys_Response) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys_Response.ProtoReflect.Descriptor instead.
func (*Keys_Response) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Keys_Response) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Keys_Response) GetPublicKeys() []*Key_Response {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type Key_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`       
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"-"`  
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key_Request) Reset() {
	*x = Key_Request{}
	mi := &file_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key_Request) ProtoMessage() {}

func (x *Key_Request) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key_Request.ProtoReflect.Descriptor instead.
func (*Key_Request) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Key_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Key_Request) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Key_Request) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type Key_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	LockedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key_Response) Reset() {
	*x = Key_Response{}
	mi := &file_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key_Response) ProtoMessage() {}

func (x *Key_Response) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key_Response.ProtoReflect.Descriptor instead.
func (*Key_Response) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Key_Response) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Key_Response) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Key_Response) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Key_Response) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Key_Response) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Key_Response) GetLockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedAt
	}
	return nil
}

func (x *Key_Response) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Key_Response) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Key_Response) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddKey_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"-"`  
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKey_Request) Reset() {
	*x = AddKey_Request{}
	mi := &file_key_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKey_Request) ProtoMessage() {}

func (x *AddKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKey_Request.ProtoReflect.Descriptor instead.
func (*AddKey_Request) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AddKey_Request) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *AddKey_Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddKey_Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AddKey_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKey_Response) Reset() {
	*x = AddKey_Response{}
	mi := &file_key_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKey_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKey_Response) ProtoMessage() {}

func (x *AddKey_Response) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKey_Response.ProtoReflect.Descriptor instead.
func (*AddKey_Response) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AddKey_Response) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AddKey_Response) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type UpdateKey_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"-"`  
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKey_Request) Reset() {
	*x = UpdateKey_Request{}
	mi := &file_key_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKey_Request) ProtoMessage() {}

func (x *UpdateKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKey_Request.ProtoReflect.Descriptor instead.
func (*UpdateKey_Request) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateKey_Request) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UpdateKey_Request) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UpdateKey_Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateKey_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKey_Response) Reset() {
	*x = UpdateKey_Response{}
	mi := &file_key_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKey_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKey_Response) ProtoMessage() {}

func (x *UpdateKey_Response) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKey_Response.ProtoReflect.Descriptor instead.
func (*UpdateKey_Response) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{4, 1}
}

type DeleteKey_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"-"`  
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKey_Request) Reset() {
	*x = DeleteKey_Request{}
	mi := &file_key_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey_Request) ProtoMessage() {}

func (x *DeleteKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey_Request.ProtoReflect.Descriptor instead.
func (*DeleteKey_Request) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DeleteKey_Request) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *DeleteKey_Request) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKey_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKey_Response) Reset() {
	*x = DeleteKey_Response{}
	mi := &file_key_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKey_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey_Response) ProtoMessage() {}

func (x *DeleteKey_Response) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey_Response.ProtoReflect.Descriptor instead.
func (*DeleteKey_Response) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{5, 1}
}

type GenerateSSHKey_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyType       KeyType                `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=key.KeyType" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSSHKey_Request) Reset() {
	*x = GenerateSSHKey_Request{}
	mi := &file_key_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSSHKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSSHKey_Request) ProtoMessage() {}

func (x *GenerateSSHKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSSHKey_Request.ProtoReflect.Descriptor instead.
func (*GenerateSSHKey_Request) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GenerateSSHKey_Request) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_unspecified
}

type GenerateSSHKey_Response struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	KeyType    KeyType                `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=key.KeyType" json:"key_type,omitempty"`
	Uuid       string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Passphrase string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	// bytes private = 3;
	Public        string `protobuf:"bytes,4,opt,name=public,proto3" json:"public,omitempty"`
	FingerPrint   string `protobuf:"bytes,5,opt,name=finger_print,json=fingerPrint,proto3" json:"finger_print,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSSHKey_Response) Reset() {
	*x = GenerateSSHKey_Response{}
	mi := &file_key_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSSHKey_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSSHKey_Response) ProtoMessage() {}

func (x *GenerateSSHKey_Response) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSSHKey_Response.ProtoReflect.Descriptor instead.
func (*GenerateSSHKey_Response) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GenerateSSHKey_Response) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_unspecified
}

func (x *GenerateSSHKey_Response) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GenerateSSHKey_Response) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *GenerateSSHKey_Response) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *GenerateSSHKey_Response) GetFingerPrint() string {
	if x != nil {
		return x.FingerPrint
	}
	return ""
}

var File_key_proto protoreflect.FileDescriptor

const file_key_proto_rawDesc = "" +
	"\n" +
	"\tkey.proto\x12\x03key\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a0pkg/utils/protoutils/ghoster/proto/ghoster.proto\"\x8c\x01\n" +
	"\tSchemeKey\x12\x16\n" +
	"\x06public\x18\x01 \x01(\tR\x06public\x12\x1e\n" +
	"\aprivate\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\aprivate\x12$\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01R\n" +
	"passphrase\x12!\n" +
	"\ffinger_print\x18\x04 \x01(\tR\vfingerPrint\"\xf6\x01\n" +
	"\x04Keys\x1a\x97\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12*\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprofileId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x1aT\n" +
	"\bResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x122\n" +
	"\vpublic_keys\x18\x03 \x03(\v2\x11.key.Key.ResponseR\n" +
	"publicKeys\"\x92\x04\n" +
	"\x03Key\x1at\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12*\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprofileId\x12\"\n" +
	"\x06key_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x05keyId\x1a\x94\x03\n" +
	"\bResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12#\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\tprofileId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x03key\x18\x04 \x01(\tB\x04\x88\xb5\x18\x01R\x03key\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x12=\n" +
	"\tlocked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\blockedAt\x12A\n" +
	"\varchived_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\n" +
	"archivedAt\x12?\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc7\x01\n" +
	"\x06AddKey\x1ax\n" +
	"\aRequest\x12*\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprofileId\x12#\n" +
	"\x05title\x18\x02 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x03\x18\x80\x01R\x05title\x12\x1c\n" +
	"\x03key\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10FR\x03key\x1aC\n" +
	"\bResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\"\x97\x01\n" +
	"\tUpdateKey\x1a~\n" +
	"\aRequest\x12*\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprofileId\x12\"\n" +
	"\x06key_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x05keyId\x12#\n" +
	"\x05title\x18\x03 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x03\x18\x80\x01R\x05title\x1a\n" +
	"\n" +
	"\bResponse\"r\n" +
	"\tDeleteKey\x1aY\n" +
	"\aRequest\x12*\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprofileId\x12\"\n" +
	"\x06key_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x05keyId\x1a\n" +
	"\n" +
	"\bResponse\"\xf1\x01\n" +
	"\x0eGenerateSSHKey\x1a:\n" +
	"\aRequest\x12/\n" +
	"\bkey_type\x18\x01 \x01(\x0e2\f.key.KeyTypeB\x06\xbaH\x03\xc8\x01\x01R\akeyType\x1a\xa2\x01\n" +
	"\bResponse\x12'\n" +
	"\bkey_type\x18\x01 \x01(\x0e2\f.key.KeyTypeR\akeyType\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tR\n" +
	"passphrase\x12\x16\n" +
	"\x06public\x18\x04 \x01(\tR\x06public\x12!\n" +
	"\ffinger_print\x18\x05 \x01(\tR\vfingerPrint*;\n" +
	"\aKeyType\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\v\n" +
	"\aed25519\x10\x01\x12\t\n" +
	"\x05ecdsa\x10\x02\x12\a\n" +
	"\x03rsa\x10\x032\xf2\x02\n" +
	"\vKeyHandlers\x12/\n" +
	"\x04Keys\x12\x11.key.Keys.Request\x1a\x12.key.Keys.Response\"\x00\x12,\n" +
	"\x03Key\x12\x10.key.Key.Request\x1a\x11.key.Key.Response\"\x00\x125\n" +
	"\x06AddKey\x12\x13.key.AddKey.Request\x1a\x14.key.AddKey.Response\"\x00\x12>\n" +
	"\tUpdateKey\x12\x16.key.UpdateKey.Request\x1a\x17.key.UpdateKey.Response\"\x00\x12>\n" +
	"\tDeleteKey\x12\x16.key.DeleteKey.Request\x1a\x17.key.DeleteKey.Response\"\x00\x12M\n" +
	"\x0eGenerateSSHKey\x12\x1b.key.GenerateSSHKey.Request\x1a\x1c.key.GenerateSSHKey.Response\"\x00B6Z4github.com/werbot/werbot/internal/core/key/proto/keyb\x06proto3"

var (
	file_key_proto_rawDescOnce sync.Once
	file_key_proto_rawDescData []byte
)

func file_key_proto_rawDescGZIP() []byte {
	file_key_proto_rawDescOnce.Do(func() {
		file_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)))
	})
	return file_key_proto_rawDescData
}

var file_key_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_key_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_key_proto_goTypes = []any{
	(KeyType)(0),                    // 0: key.KeyType
	(*SchemeKey)(nil),               // 1: key.SchemeKey
	(*Keys)(nil),                    // 2: key.Keys
	(*Key)(nil),                     // 3: key.Key
	(*AddKey)(nil),                  // 4: key.AddKey
	(*UpdateKey)(nil),               // 5: key.UpdateKey
	(*DeleteKey)(nil),               // 6: key.DeleteKey
	(*GenerateSSHKey)(nil),          // 7: key.GenerateSSHKey
	(*Keys_Request)(nil),            // 8: key.Keys.Request
	(*Keys_Response)(nil),           // 9: key.Keys.Response
	(*Key_Request)(nil),             // 10: key.Key.Request
	(*Key_Response)(nil),            // 11: key.Key.Response
	(*AddKey_Request)(nil),          // 12: key.AddKey.Request
	(*AddKey_Response)(nil),         // 13: key.AddKey.Response
	(*UpdateKey_Request)(nil),       // 14: key.UpdateKey.Request
	(*UpdateKey_Response)(nil),      // 15: key.UpdateKey.Response
	(*DeleteKey_Request)(nil),       // 16: key.DeleteKey.Request
	(*DeleteKey_Response)(nil),      // 17: key.DeleteKey.Response
	(*GenerateSSHKey_Request)(nil),  // 18: key.GenerateSSHKey.Request
	(*GenerateSSHKey_Response)(nil), // 19: key.GenerateSSHKey.Response
	(*timestamppb.Timestamp)(nil),   // 20: google.protobuf.Timestamp
}
var file_key_proto_depIdxs = []int32{
	11, // 0: key.Keys.Response.public_keys:type_name -> key.Key.Response
	20, // 1: key.Key.Response.locked_at:type_name -> google.protobuf.Timestamp
	20, // 2: key.Key.Response.archived_at:type_name -> google.protobuf.Timestamp
	20, // 3: key.Key.Response.updated_at:type_name -> google.protobuf.Timestamp
	20, // 4: key.Key.Response.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: key.GenerateSSHKey.Request.key_type:type_name -> key.KeyType
	0,  // 6: key.GenerateSSHKey.Response.key_type:type_name -> key.KeyType
	8,  // 7: key.KeyHandlers.Keys:input_type -> key.Keys.Request
	10, // 8: key.KeyHandlers.Key:input_type -> key.Key.Request
	12, // 9: key.KeyHandlers.AddKey:input_type -> key.AddKey.Request
	14, // 10: key.KeyHandlers.UpdateKey:input_type -> key.UpdateKey.Request
	16, // 11: key.KeyHandlers.DeleteKey:input_type -> key.DeleteKey.Request
	18, // 12: key.KeyHandlers.GenerateSSHKey:input_type -> key.GenerateSSHKey.Request
	9,  // 13: key.KeyHandlers.Keys:output_type -> key.Keys.Response
	11, // 14: key.KeyHandlers.Key:output_type -> key.Key.Response
	13, // 15: key.KeyHandlers.AddKey:output_type -> key.AddKey.Response
	15, // 16: key.KeyHandlers.UpdateKey:output_type -> key.UpdateKey.Response
	17, // 17: key.KeyHandlers.DeleteKey:output_type -> key.DeleteKey.Response
	19, // 18: key.KeyHandlers.GenerateSSHKey:output_type -> key.GenerateSSHKey.Response
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_key_proto_init() }
func file_key_proto_init() {
	if File_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_proto_goTypes,
		DependencyIndexes: file_key_proto_depIdxs,
		EnumInfos:         file_key_proto_enumTypes,
		MessageInfos:      file_key_proto_msgTypes,
	}.Build()
	File_key_proto = out.File
	file_key_proto_goTypes = nil
	file_key_proto_depIdxs = nil
}
