issues:
  exclude-rules:
    - linters:
        - gosimple
      text: "S1002: should omit comparison to bool constant"
    - linters:
        - revive
      text: "exported: exported const"
    - linters:
        - unused
      path: 'operator/controllers/resources/(.+)_controller_test\.go'
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  nolintlint:
    allow-unused: true # Enabled because of conditional builds / build tags.
    require-explanation: true
    require-specific: true
  gosec:
    excludes:
      - G202 # SQL string concatenation
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G501 # Detect the usage of DES, RC4, MD5 or SHA1

linters:
  disable-all: true
  enable:
    - bodyclose
    # - dupl
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - gosec
    - sqlclosecheck
    - goprintffuncname
    - exportloopref
    - unparam
    - whitespace
    - staticcheck
    - unconvert
    - unused
    - goconst
    - gocritic

