package scheme

import (
	"net/http"
	"testing"

	"github.com/werbot/werbot/internal/trace"
	"github.com/werbot/werbot/internal/utils/test"
)

func TestHandler_profileSchemes(t *testing.T) {
	app, teardownTestCase, adminHeader, userHeader := setupTest(t)
	defer teardownTestCase(t)

	testTable := []test.APITable{
		{ // unauthorized request
			Name:       "test0_01",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile"),
			StatusCode: 401,
			Body:       test.BodyUnauthorized,
		},
		{ // ADMIN:
			Name:       "test1_01",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile"),
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(7),
				"result.total.300": float64(2),
				"result.total.400": float64(2),
				"result.total.500": float64(0),
				"result.total.600": float64(0),
				"result.schemes":   "*",
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN: limit
			Name:       "test1_02",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile") + "?limit=5",
			StatusCode: 200,
			Body: test.BodyTable{
				"code":                         float64(200),
				"message":                      "Profile schemes",
				"result.total.100":             float64(5),
				"result.total.200":             float64(7),
				"result.total.300":             float64(2),
				"result.total.400":             float64(2),
				"result.total.500":             float64(0),
				"result.total.600":             float64(0),
				"result.schemes.0.active":      "*",
				"result.schemes.0.alias":       "*",
				"result.schemes.0.auth_method": "*",
				"result.schemes.0.project_id":  "*",
				"result.schemes.0.scheme_type": "*",
				"result.schemes.0.title":       "*",
				"result.schemes.5":             nil,
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN:
			Name:       "test1_03",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile", "desktop"),
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(7),
				"result.total.300": float64(2),
				"result.total.400": float64(2),
				"result.total.500": float64(0),
				"result.total.600": float64(0),
				"result.schemes.0": "*",
				"result.schemes.1": "*",
				"result.schemes.2": nil,
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN: desktop schemes with limit
			Name:       "test1_04",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile", "desktop") + "?limit=1",
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(7),
				"result.total.300": float64(2),
				"result.total.400": float64(2),
				"result.total.500": float64(0),
				"result.total.600": float64(0),
				"result.schemes.0": "*",
				"result.schemes.1": nil,
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN: default request with fake profile UUID
			Name:       "test1_05",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile") + "?profile_id=" + test.ConstFakeID,
			StatusCode: 404,
			Body: test.BodyTable{
				"code":    float64(404),
				"message": "Not Found",
				"result":  trace.MsgSchemeNotFound,
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN: default request with real profile UUID
			Name:       "test1_06",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile") + "?profile_id=" + test.ConstUserID,
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes":   "*",
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN: default request with real profile UUID select scheme
			Name:       "test1_07",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile", "desktop") + "?profile_id=" + test.ConstUserID,
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes.2": nil,
			},
			RequestHeaders: adminHeader,
		},
		{ // ADMIN:
			Name:           "test0_02",
			Method:         http.MethodGet,
			Path:           test.PathGluing(pathSchemes, "profile", "test"),
			StatusCode:     404,
			Body:           test.BodyNotFound,
			RequestHeaders: adminHeader,
		},

		{ // USER:
			Name:       "test2_01",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile"),
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes":   "*",
			},
			RequestHeaders: userHeader,
		},
		{ // USER: limit
			Name:       "test2_02",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile") + "?limit=5",
			StatusCode: 200,
			Body: test.BodyTable{
				"code":                         float64(200),
				"message":                      "Profile schemes",
				"result.total.100":             float64(5),
				"result.total.200":             float64(10),
				"result.total.300":             float64(2),
				"result.total.400":             float64(3),
				"result.total.500":             float64(8),
				"result.total.600":             float64(2),
				"result.schemes.0.active":      "*",
				"result.schemes.0.alias":       "*",
				"result.schemes.0.auth_method": "*",
				"result.schemes.0.project_id":  "*",
				"result.schemes.0.scheme_type": "*",
				"result.schemes.0.title":       "*",
				"result.schemes.5":             nil,
			},
			RequestHeaders: userHeader,
		},
		{ // USER:
			Name:       "test2_03",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile", "desktop"),
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes.0": "*",
				"result.schemes.1": "*",
				"result.schemes.2": nil,
			},
			RequestHeaders: userHeader,
		},
		{ // USER: desktop schemes with limit
			Name:       "test2_04",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile", "desktop") + "?limit=1",
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes.0": "*",
				"result.schemes.1": nil,
			},
			RequestHeaders: userHeader,
		},
		{ // USER: default request with fake profile UUID
			Name:       "test2_05",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile") + "?profile_id=" + test.ConstFakeID,
			StatusCode: 404,
			Body: test.BodyTable{
				"code":    float64(404),
				"message": "Not Found",
				"result":  trace.MsgSchemeNotFound,
			},
			RequestHeaders: adminHeader,
		},
		{ // USER: default request with real profile UUID
			Name:       "test2_06",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile") + "?profile_id=" + test.ConstAdminID,
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes":   "*",
			},
			RequestHeaders: userHeader,
		},
		{ // USER: default request with real profile UUID select scheme
			Name:       "test2_07",
			Method:     http.MethodGet,
			Path:       test.PathGluing(pathSchemes, "profile", "desktop") + "?profile_id=" + test.ConstAdminID,
			StatusCode: 200,
			Body: test.BodyTable{
				"code":             float64(200),
				"message":          "Profile schemes",
				"result.total.100": float64(5),
				"result.total.200": float64(10),
				"result.total.300": float64(2),
				"result.total.400": float64(3),
				"result.total.500": float64(8),
				"result.total.600": float64(2),
				"result.schemes.2": nil,
			},
			RequestHeaders: userHeader,
		},
	}

	test.RunCaseAPITests(t, app, testTable)
}
