name: "🤔 Question"
title: "\U0001F917 [Question]: "
description: Ask a question so we can help you easily.
labels: ["🤔 Question"]

body:
  - type: markdown
    id: notice
    attributes:
      value: |
        ### Notice
        - If you think this is just a bug, open the issue with the **☢️ Bug Report** template.
        - If you have a suggestion for a werbot feature you would like to see, open the issue with the **✏️ Feature Request** template.
        - Write your issue with clear and understandable English.
  - type: textarea
    id: description
    attributes:
      label: "Question Description"
      description: "A clear and detailed description of the question."
      placeholder: "Explain your question clearly, and in detail."
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: "Code Snippet (optional)"
      description: "Code snippet may be really helpful to describe some features."
      placeholder: "Share a code snippet to explain the feature better."
      render: go
      value: |
        package main

        import "fmt"

        func main() {
          fmt.Print("hello word")
        }
  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist:"
      description: "By submitting this issue, you confirm that:"
      options:
        - label: "I agree to follow werbot's [Code of Conduct](https://github.com/werbot/.github/blob/main/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have checked for existing issues that describe my questions prior to opening this one."
          required: true
        - label: "I understand that improperly formatted questions may be closed without explanation."
          required: true
