#!/usr/bin/env bash

set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/helper

arr_process=(__debug_bin vite)
for process in "${arr_process[@]}"; do
  if pkill -f "$process" >/dev/null; then
    print_header "Killing $process process"
    print_answer "SUCCESS" green
  fi
done

print_header "Leaning garbage and inactive containers"
if [ -d ${ROOT_PATH}/web/dist ]; then
  rm -rf ${ROOT_PATH}/web/dist
fi

rm -rf ${ROOT_PATH}/bin/* ${ROOT_PATH}/dist/
docker system prune --all --volumes --force >/dev/null 2>&1
docker image prune --filter "dangling=true" --force >/dev/null 2>&1
print_answer "SUCCESS" green

if pgrep -f "postgres.*9876" >/dev/null; then
  print_header "Killing embedded postgres"
  kill $(pgrep -f "postgres.*9876")
  print_answer "SUCCESS" green
fi
