#!/usr/bin/env bash

set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/helper

arr_process=(__debug_bin vite)
for process in "${arr_process[@]}"; do
  for pid in $(echo $(ps ax | grep $process | grep -v grep | awk '{print $1}')); do
    print_header "Killing $process process $pid"
    kill $pid
    print_answer "SUCCESS" green
  done
done

print_header "Leaning garbage and inactive containers"
if [ -d ${ROOT_PATH}/web/dist ]; then
  rm -rf ${ROOT_PATH}/web/dist
fi

rm -rf ${ROOT_PATH}/bin/* ${ROOT_PATH}/dist/
docker system prune --all --volumes --force >/dev/null 2>&1
docker image prune --filter "dangling=true" --force >/dev/null 2>&1
print_answer "SUCCESS" green
