networks:
  private:
    #internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.16.0.0/16
          gateway: 10.16.0.1

services:
  testdb:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      # Uses a tmpfs volume to make tests extremely fast. The data in test
      # databases is not persisted across restarts, nor does it need to be.
      - type: tmpfs
        target: /var/lib/postgresql/data/
    command:
      - "postgres"
      - "-c" # turn off fsync for speed
      - "fsync=off"
      - "-c" # log everything for debugging
      - "log_statement=none"
    ports:
      - "5433:5432"

  worker:
    image: hibiken/asynqmon:latest
    restart: unless-stopped
    ports:
      - 8085:8085
    command: --port=8085 --redis-addr=service.redis:6379 --redis-db=1 --redis-password=${REDIS_PASSWORD:-redisPassword}
    networks:
      - private
