// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailTemplate int32

const (
	MailTemplate_unspecified                   MailTemplate = 0
	MailTemplate_password_reset                MailTemplate = 1
	MailTemplate_project_invite                MailTemplate = 2
	MailTemplate_account_deletion_confirmation MailTemplate = 3
	MailTemplate_account_deletion_info         MailTemplate = 4
)

// Enum value maps for MailTemplate.
var (
	MailTemplate_name = map[int32]string{
		0: "unspecified",
		1: "password_reset",
		2: "project_invite",
		3: "account_deletion_confirmation",
		4: "account_deletion_info",
	}
	MailTemplate_value = map[string]int32{
		"unspecified":                   0,
		"password_reset":                1,
		"project_invite":                2,
		"account_deletion_confirmation": 3,
		"account_deletion_info":         4,
	}
)

func (x MailTemplate) Enum() *MailTemplate {
	p := new(MailTemplate)
	*p = x
	return p
}

func (x MailTemplate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailTemplate) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (MailTemplate) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x MailTemplate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailTemplate.Descriptor instead.
func (MailTemplate) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto\x12\x10notificationenum*\x85\x01\n" +
	"\fMailTemplate\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\x12\n" +
	"\x0epassword_reset\x10\x01\x12\x12\n" +
	"\x0eproject_invite\x10\x02\x12!\n" +
	"\x1daccount_deletion_confirmation\x10\x03\x12\x19\n" +
	"\x15account_deletion_info\x10\x04B@Z>github.com/werbot/werbot/internal/core/notification/proto/enumb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_proto_goTypes = []any{
	(MailTemplate)(0), // 0: notificationenum.MailTemplate
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
