// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	enum "github.com/werbot/werbot/internal/core/notification/proto/enum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// rpc SendMail
type SendMail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMail) Reset() {
	*x = SendMail{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMail) ProtoMessage() {}

func (x *SendMail) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMail.ProtoReflect.Descriptor instead.
func (*SendMail) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type SendMail_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Template      enum.MailTemplate      `protobuf:"varint,3,opt,name=template,proto3,enum=notificationenum.MailTemplate" json:"template,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMail_Request) Reset() {
	*x = SendMail_Request{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMail_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMail_Request) ProtoMessage() {}

func (x *SendMail_Request) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMail_Request.ProtoReflect.Descriptor instead.
func (*SendMail_Request) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SendMail_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMail_Request) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMail_Request) GetTemplate() enum.MailTemplate {
	if x != nil {
		return x.Template
	}
	return enum.MailTemplate(0)
}

func (x *SendMail_Request) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendMail_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMail_Response) Reset() {
	*x = SendMail_Response{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMail_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMail_Response) ProtoMessage() {}

func (x *SendMail_Response) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMail_Response.ProtoReflect.Descriptor instead.
func (*SendMail_Response) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 1}
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x13notificationmessage\x1a0internal/core/notification/proto/enum/enum.proto\"\x8c\x02\n" +
	"\bSendMail\x1a\xf3\x01\n" +
	"\aRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12:\n" +
	"\btemplate\x18\x03 \x01(\x0e2\x1e.notificationenum.MailTemplateR\btemplate\x12C\n" +
	"\x04data\x18\x04 \x03(\v2/.notificationmessage.SendMail.Request.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\n" +
	"\n" +
	"\bResponseBCZAgithub.com/werbot/werbot/internal/core/notification/proto/messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(*SendMail)(nil),          // 0: notificationmessage.SendMail
	(*SendMail_Request)(nil),  // 1: notificationmessage.SendMail.Request
	(*SendMail_Response)(nil), // 2: notificationmessage.SendMail.Response
	nil,                       // 3: notificationmessage.SendMail.Request.DataEntry
	(enum.MailTemplate)(0),    // 4: notificationenum.MailTemplate
}
var file_message_proto_depIdxs = []int32{
	4, // 0: notificationmessage.SendMail.Request.template:type_name -> notificationenum.MailTemplate
	3, // 1: notificationmessage.SendMail.Request.data:type_name -> notificationmessage.SendMail.Request.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
