// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: utility.proto

package utility

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// rpc GetInfo
type ListCountries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCountries) Reset() {
	*x = ListCountries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utility_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCountries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountries) ProtoMessage() {}

func (x *ListCountries) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountries.ProtoReflect.Descriptor instead.
func (*ListCountries) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{0}
}

type ListCountries_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListCountries_Request) Reset() {
	*x = ListCountries_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utility_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCountries_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountries_Request) ProtoMessage() {}

func (x *ListCountries_Request) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountries_Request.ProtoReflect.Descriptor instead.
func (*ListCountries_Request) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListCountries_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCountries_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Countries []*ListCountries_Response_Country `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
}

func (x *ListCountries_Response) Reset() {
	*x = ListCountries_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utility_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCountries_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountries_Response) ProtoMessage() {}

func (x *ListCountries_Response) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountries_Response.ProtoReflect.Descriptor instead.
func (*ListCountries_Response) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ListCountries_Response) GetCountries() []*ListCountries_Response_Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type ListCountries_Response_Country struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListCountries_Response_Country) Reset() {
	*x = ListCountries_Response_Country{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utility_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCountries_Response_Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountries_Response_Country) ProtoMessage() {}

func (x *ListCountries_Response_Country) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountries_Response_Country.ProtoReflect.Descriptor instead.
func (*ListCountries_Response_Country) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ListCountries_Response_Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ListCountries_Response_Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_utility_proto protoreflect.FileDescriptor

var file_utility_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x1a, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x84, 0x01, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x75, 0x74,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a,
	0x31, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x32, 0x65, 0x0a, 0x0f, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x73, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x72, 0x62, 0x6f, 0x74, 0x2f, 0x77,
	0x65, 0x72, 0x62, 0x6f, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utility_proto_rawDescOnce sync.Once
	file_utility_proto_rawDescData = file_utility_proto_rawDesc
)

func file_utility_proto_rawDescGZIP() []byte {
	file_utility_proto_rawDescOnce.Do(func() {
		file_utility_proto_rawDescData = protoimpl.X.CompressGZIP(file_utility_proto_rawDescData)
	})
	return file_utility_proto_rawDescData
}

var file_utility_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_utility_proto_goTypes = []interface{}{
	(*ListCountries)(nil),                  // 0: utility.ListCountries
	(*ListCountries_Request)(nil),          // 1: utility.ListCountries.Request
	(*ListCountries_Response)(nil),         // 2: utility.ListCountries.Response
	(*ListCountries_Response_Country)(nil), // 3: utility.ListCountries.Response.Country
}
var file_utility_proto_depIdxs = []int32{
	3, // 0: utility.ListCountries.Response.countries:type_name -> utility.ListCountries.Response.Country
	1, // 1: utility.UtilityHandlers.ListCountries:input_type -> utility.ListCountries.Request
	2, // 2: utility.UtilityHandlers.ListCountries:output_type -> utility.ListCountries.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_utility_proto_init() }
func file_utility_proto_init() {
	if File_utility_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_utility_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCountries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utility_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCountries_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utility_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCountries_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utility_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCountries_Response_Country); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utility_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utility_proto_goTypes,
		DependencyIndexes: file_utility_proto_depIdxs,
		MessageInfos:      file_utility_proto_msgTypes,
	}.Build()
	File_utility_proto = out.File
	file_utility_proto_rawDesc = nil
	file_utility_proto_goTypes = nil
	file_utility_proto_depIdxs = nil
}
