// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	message "github.com/werbot/werbot/internal/core/audit/proto/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x05audit\x1a/internal/core/audit/proto/message/message.proto2\xd3\x04\n" +
	"\rAuditHandlers\x12S\n" +
	"\n" +
	"ListAudits\x12 .auditmessage.ListAudits.Request\x1a!.auditmessage.ListAudits.Response\"\x00\x12D\n" +
	"\x05Audit\x12\x1b.auditmessage.Audit.Request\x1a\x1c.auditmessage.Audit.Response\"\x00\x12M\n" +
	"\bAddAudit\x12\x1e.auditmessage.AddAudit.Request\x1a\x1f.auditmessage.AddAudit.Response\"\x00\x12V\n" +
	"\vUpdateAudit\x12!.auditmessage.UpdateAudit.Request\x1a\".auditmessage.UpdateAudit.Response\"\x00\x12V\n" +
	"\vDeleteAudit\x12!.auditmessage.DeleteAudit.Request\x1a\".auditmessage.DeleteAudit.Response\"\x00\x12V\n" +
	"\vListRecords\x12!.auditmessage.ListRecords.Request\x1a\".auditmessage.ListRecords.Response\"\x00\x12P\n" +
	"\tAddRecord\x12\x1f.auditmessage.AddRecord.Request\x1a .auditmessage.AddRecord.Response\"\x00B8Z6github.com/werbot/werbot/internal/core/audit/proto/rpcb\x06proto3"

var file_rpc_proto_goTypes = []any{
	(*message.ListAudits_Request)(nil),   // 0: auditmessage.ListAudits.Request
	(*message.Audit_Request)(nil),        // 1: auditmessage.Audit.Request
	(*message.AddAudit_Request)(nil),     // 2: auditmessage.AddAudit.Request
	(*message.UpdateAudit_Request)(nil),  // 3: auditmessage.UpdateAudit.Request
	(*message.DeleteAudit_Request)(nil),  // 4: auditmessage.DeleteAudit.Request
	(*message.ListRecords_Request)(nil),  // 5: auditmessage.ListRecords.Request
	(*message.AddRecord_Request)(nil),    // 6: auditmessage.AddRecord.Request
	(*message.ListAudits_Response)(nil),  // 7: auditmessage.ListAudits.Response
	(*message.Audit_Response)(nil),       // 8: auditmessage.Audit.Response
	(*message.AddAudit_Response)(nil),    // 9: auditmessage.AddAudit.Response
	(*message.UpdateAudit_Response)(nil), // 10: auditmessage.UpdateAudit.Response
	(*message.DeleteAudit_Response)(nil), // 11: auditmessage.DeleteAudit.Response
	(*message.ListRecords_Response)(nil), // 12: auditmessage.ListRecords.Response
	(*message.AddRecord_Response)(nil),   // 13: auditmessage.AddRecord.Response
}
var file_rpc_proto_depIdxs = []int32{
	0,  // 0: audit.AuditHandlers.ListAudits:input_type -> auditmessage.ListAudits.Request
	1,  // 1: audit.AuditHandlers.Audit:input_type -> auditmessage.Audit.Request
	2,  // 2: audit.AuditHandlers.AddAudit:input_type -> auditmessage.AddAudit.Request
	3,  // 3: audit.AuditHandlers.UpdateAudit:input_type -> auditmessage.UpdateAudit.Request
	4,  // 4: audit.AuditHandlers.DeleteAudit:input_type -> auditmessage.DeleteAudit.Request
	5,  // 5: audit.AuditHandlers.ListRecords:input_type -> auditmessage.ListRecords.Request
	6,  // 6: audit.AuditHandlers.AddRecord:input_type -> auditmessage.AddRecord.Request
	7,  // 7: audit.AuditHandlers.ListAudits:output_type -> auditmessage.ListAudits.Response
	8,  // 8: audit.AuditHandlers.Audit:output_type -> auditmessage.Audit.Response
	9,  // 9: audit.AuditHandlers.AddAudit:output_type -> auditmessage.AddAudit.Response
	10, // 10: audit.AuditHandlers.UpdateAudit:output_type -> auditmessage.UpdateAudit.Response
	11, // 11: audit.AuditHandlers.DeleteAudit:output_type -> auditmessage.DeleteAudit.Response
	12, // 12: audit.AuditHandlers.ListRecords:output_type -> auditmessage.ListRecords.Response
	13, // 13: audit.AuditHandlers.AddRecord:output_type -> auditmessage.AddRecord.Response
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
