// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member.proto

package member

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	profile "github.com/werbot/werbot/internal/core/profile/proto/profile"
	_ "github.com/werbot/werbot/pkg/utils/protoutils/ghoster/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteStatus int32

const (
	InviteStatus_unspecified InviteStatus = 0
	InviteStatus_send        InviteStatus = 1
	InviteStatus_activated   InviteStatus = 2
)

// Enum value maps for InviteStatus.
var (
	InviteStatus_name = map[int32]string{
		0: "unspecified",
		1: "send",
		2: "activated",
	}
	InviteStatus_value = map[string]int32{
		"unspecified": 0,
		"send":        1,
		"activated":   2,
	}
)

func (x InviteStatus) Enum() *InviteStatus {
	p := new(InviteStatus)
	*p = x
	return p
}

func (x InviteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_member_proto_enumTypes[0].Descriptor()
}

func (InviteStatus) Type() protoreflect.EnumType {
	return &file_member_proto_enumTypes[0]
}

func (x InviteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteStatus.Descriptor instead.
func (InviteStatus) EnumDescriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0}
}

// rpc ProjectMembers
type ProjectMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembers) Reset() {
	*x = ProjectMembers{}
	mi := &file_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembers) ProtoMessage() {}

func (x *ProjectMembers) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMembers.ProtoReflect.Descriptor instead.
func (*ProjectMembers) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0}
}

// rpc ProjectMember
type ProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{1}
}

// rpc AddProjectMember
type AddProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectMember) Reset() {
	*x = AddProjectMember{}
	mi := &file_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectMember) ProtoMessage() {}

func (x *AddProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectMember.ProtoReflect.Descriptor instead.
func (*AddProjectMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{2}
}

// rpc UpdateProjectMember
type UpdateProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectMember) Reset() {
	*x = UpdateProjectMember{}
	mi := &file_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectMember) ProtoMessage() {}

func (x *UpdateProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectMember.ProtoReflect.Descriptor instead.
func (*UpdateProjectMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{3}
}

// rpc DeleteProjectMember
type DeleteProjectMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectMember) Reset() {
	*x = DeleteProjectMember{}
	mi := &file_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectMember) ProtoMessage() {}

func (x *DeleteProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectMember.ProtoReflect.Descriptor instead.
func (*DeleteProjectMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{4}
}

// rpc ProfilesWithoutProject
type ProfilesWithoutProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesWithoutProject) Reset() {
	*x = ProfilesWithoutProject{}
	mi := &file_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesWithoutProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesWithoutProject) ProtoMessage() {}

func (x *ProfilesWithoutProject) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesWithoutProject.ProtoReflect.Descriptor instead.
func (*ProfilesWithoutProject) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{5}
}

// SchemeMembers
type SchemeMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemeMembers) Reset() {
	*x = SchemeMembers{}
	mi := &file_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeMembers) ProtoMessage() {}

func (x *SchemeMembers) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeMembers.ProtoReflect.Descriptor instead.
func (*SchemeMembers) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{6}
}

// SchemeMember
type SchemeMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemeMember) Reset() {
	*x = SchemeMember{}
	mi := &file_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeMember) ProtoMessage() {}

func (x *SchemeMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeMember.ProtoReflect.Descriptor instead.
func (*SchemeMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{7}
}

// AddSchemeMember
type AddSchemeMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSchemeMember) Reset() {
	*x = AddSchemeMember{}
	mi := &file_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSchemeMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSchemeMember) ProtoMessage() {}

func (x *AddSchemeMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSchemeMember.ProtoReflect.Descriptor instead.
func (*AddSchemeMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{8}
}

// UpdateSchemeMember
type UpdateSchemeMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemeMember) Reset() {
	*x = UpdateSchemeMember{}
	mi := &file_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemeMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemeMember) ProtoMessage() {}

func (x *UpdateSchemeMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemeMember.ProtoReflect.Descriptor instead.
func (*UpdateSchemeMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{9}
}

// DeleteSchemeMember
type DeleteSchemeMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemeMember) Reset() {
	*x = DeleteSchemeMember{}
	mi := &file_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemeMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemeMember) ProtoMessage() {}

func (x *DeleteSchemeMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemeMember.ProtoReflect.Descriptor instead.
func (*DeleteSchemeMember) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{10}
}

// rpc MembersWithoutScheme
type MembersWithoutScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersWithoutScheme) Reset() {
	*x = MembersWithoutScheme{}
	mi := &file_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersWithoutScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersWithoutScheme) ProtoMessage() {}

func (x *MembersWithoutScheme) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersWithoutScheme.ProtoReflect.Descriptor instead.
func (*MembersWithoutScheme) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{11}
}

type ProjectMembers_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`       
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"-"`        
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"-"`  
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembers_Request) Reset() {
	*x = ProjectMembers_Request{}
	mi := &file_member_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembers_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembers_Request) ProtoMessage() {}

func (x *ProjectMembers_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMembers_Request.ProtoReflect.Descriptor instead.
func (*ProjectMembers_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProjectMembers_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *ProjectMembers_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ProjectMembers_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMembers_Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProjectMembers_Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProjectMembers_Request) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ProjectMembers_Response struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         int32                     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Members       []*ProjectMember_Response `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembers_Response) Reset() {
	*x = ProjectMembers_Response{}
	mi := &file_member_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembers_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembers_Response) ProtoMessage() {}

func (x *ProjectMembers_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMembers_Response.ProtoReflect.Descriptor instead.
func (*ProjectMembers_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProjectMembers_Response) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProjectMembers_Response) GetMembers() []*ProjectMember_Response {
	if x != nil {
		return x.Members
	}
	return nil
}

type ProjectMember_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`       
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"-"`        
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"-"`  
	MemberId      string                 `protobuf:"bytes,4,opt,name=member_id,json=memberId,proto3" json:"-"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember_Request) Reset() {
	*x = ProjectMember_Request{}
	mi := &file_member_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember_Request) ProtoMessage() {}

func (x *ProjectMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember_Request.ProtoReflect.Descriptor instead.
func (*ProjectMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ProjectMember_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *ProjectMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ProjectMember_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMember_Request) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type ProjectMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	MemberId      string                 `protobuf:"bytes,5,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,6,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Role          profile.Role           `protobuf:"varint,8,opt,name=role,proto3,enum=profile.Role" json:"role,omitempty"`
	Active        bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	Online        bool                   `protobuf:"varint,10,opt,name=online,proto3" json:"online,omitempty"`
	SchemesCount  int32                  `protobuf:"varint,11,opt,name=schemes_count,json=schemesCount,proto3" json:"schemes_count,omitempty"`
	LockedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember_Response) Reset() {
	*x = ProjectMember_Response{}
	mi := &file_member_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember_Response) ProtoMessage() {}

func (x *ProjectMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember_Response.ProtoReflect.Descriptor instead.
func (*ProjectMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ProjectMember_Response) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ProjectMember_Response) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *ProjectMember_Response) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMember_Response) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectMember_Response) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ProjectMember_Response) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProjectMember_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectMember_Response) GetRole() profile.Role {
	if x != nil {
		return x.Role
	}
	return profile.Role(0)
}

func (x *ProjectMember_Response) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ProjectMember_Response) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *ProjectMember_Response) GetSchemesCount() int32 {
	if x != nil {
		return x.SchemesCount
	}
	return 0
}

func (x *ProjectMember_Response) GetLockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedAt
	}
	return nil
}

func (x *ProjectMember_Response) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *ProjectMember_Response) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProjectMember_Response) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddProjectMember_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"-"`        
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"-"`  
	ProfileId     string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Role          profile.Role           `protobuf:"varint,4,opt,name=role,proto3,enum=profile.Role" json:"-"`  
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectMember_Request) Reset() {
	*x = AddProjectMember_Request{}
	mi := &file_member_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectMember_Request) ProtoMessage() {}

func (x *AddProjectMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectMember_Request.ProtoReflect.Descriptor instead.
func (*AddProjectMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AddProjectMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AddProjectMember_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddProjectMember_Request) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *AddProjectMember_Request) GetRole() profile.Role {
	if x != nil {
		return x.Role
	}
	return profile.Role(0)
}

func (x *AddProjectMember_Request) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type AddProjectMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectMember_Response) Reset() {
	*x = AddProjectMember_Response{}
	mi := &file_member_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectMember_Response) ProtoMessage() {}

func (x *AddProjectMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectMember_Response.ProtoReflect.Descriptor instead.
func (*AddProjectMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{2, 1}
}

func (x *AddProjectMember_Response) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type UpdateProjectMember_Request struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin   bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`       
	OwnerId   string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"-"`        
	ProjectId string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"-"`  
	MemberId  string                 `protobuf:"bytes,4,opt,name=member_id,json=memberId,proto3" json:"-"`     
	// Types that are valid to be assigned to Setting:
	//
	//	*UpdateProjectMember_Request_Role
	//	*UpdateProjectMember_Request_Active
	Setting       isUpdateProjectMember_Request_Setting `protobuf_oneof:"setting"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectMember_Request) Reset() {
	*x = UpdateProjectMember_Request{}
	mi := &file_member_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectMember_Request) ProtoMessage() {}

func (x *UpdateProjectMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectMember_Request.ProtoReflect.Descriptor instead.
func (*UpdateProjectMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateProjectMember_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UpdateProjectMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UpdateProjectMember_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectMember_Request) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *UpdateProjectMember_Request) GetSetting() isUpdateProjectMember_Request_Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *UpdateProjectMember_Request) GetRole() profile.Role {
	if x != nil {
		if x, ok := x.Setting.(*UpdateProjectMember_Request_Role); ok {
			return x.Role
		}
	}
	return profile.Role(0)
}

func (x *UpdateProjectMember_Request) GetActive() bool {
	if x != nil {
		if x, ok := x.Setting.(*UpdateProjectMember_Request_Active); ok {
			return x.Active
		}
	}
	return false
}

type isUpdateProjectMember_Request_Setting interface {
	isUpdateProjectMember_Request_Setting()
}

type UpdateProjectMember_Request_Role struct {
	Role profile.Role `protobuf:"varint,5,opt,name=role,proto3,enum=profile.Role,oneof"`
}

type UpdateProjectMember_Request_Active struct {
	Active bool `protobuf:"varint,6,opt,name=active,proto3,oneof"`
}

func (*UpdateProjectMember_Request_Role) isUpdateProjectMember_Request_Setting() {}

func (*UpdateProjectMember_Request_Active) isUpdateProjectMember_Request_Setting() {}

type UpdateProjectMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectMember_Response) Reset() {
	*x = UpdateProjectMember_Response{}
	mi := &file_member_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectMember_Response) ProtoMessage() {}

func (x *UpdateProjectMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectMember_Response.ProtoReflect.Descriptor instead.
func (*UpdateProjectMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{3, 1}
}

type DeleteProjectMember_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"-"`        
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"-"`  
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"-"`     
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectMember_Request) Reset() {
	*x = DeleteProjectMember_Request{}
	mi := &file_member_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectMember_Request) ProtoMessage() {}

func (x *DeleteProjectMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectMember_Request.ProtoReflect.Descriptor instead.
func (*DeleteProjectMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DeleteProjectMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DeleteProjectMember_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteProjectMember_Request) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type DeleteProjectMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectMember_Response) Reset() {
	*x = DeleteProjectMember_Response{}
	mi := &file_member_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectMember_Response) ProtoMessage() {}

func (x *DeleteProjectMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectMember_Response.ProtoReflect.Descriptor instead.
func (*DeleteProjectMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{4, 1}
}

type ProfilesWithoutProject_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`       
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"-"`  
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesWithoutProject_Request) Reset() {
	*x = ProfilesWithoutProject_Request{}
	mi := &file_member_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesWithoutProject_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesWithoutProject_Request) ProtoMessage() {}

func (x *ProfilesWithoutProject_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesWithoutProject_Request.ProtoReflect.Descriptor instead.
func (*ProfilesWithoutProject_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ProfilesWithoutProject_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *ProfilesWithoutProject_Request) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProfilesWithoutProject_Request) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ProfilesWithoutProject_Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProfilesWithoutProject_Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProfilesWithoutProject_Request) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ProfilesWithoutProject_Response struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Total         int32                             `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Profiles      []*ProfilesWithoutProject_Profile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesWithoutProject_Response) Reset() {
	*x = ProfilesWithoutProject_Response{}
	mi := &file_member_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesWithoutProject_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesWithoutProject_Response) ProtoMessage() {}

func (x *ProfilesWithoutProject_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesWithoutProject_Response.ProtoReflect.Descriptor instead.
func (*ProfilesWithoutProject_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ProfilesWithoutProject_Response) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProfilesWithoutProject_Response) GetProfiles() []*ProfilesWithoutProject_Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type ProfilesWithoutProject_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesWithoutProject_Profile) Reset() {
	*x = ProfilesWithoutProject_Profile{}
	mi := &file_member_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesWithoutProject_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesWithoutProject_Profile) ProtoMessage() {}

func (x *ProfilesWithoutProject_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesWithoutProject_Profile.ProtoReflect.Descriptor instead.
func (*ProfilesWithoutProject_Profile) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{5, 2}
}

func (x *ProfilesWithoutProject_Profile) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfilesWithoutProject_Profile) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ProfilesWithoutProject_Profile) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ProfilesWithoutProject_Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SchemeMembers_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`    
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"-"`     
	SchemeId      string                 `protobuf:"bytes,3,opt,name=scheme_id,json=schemeId,proto3" json:"-"`  
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemeMembers_Request) Reset() {
	*x = SchemeMembers_Request{}
	mi := &file_member_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeMembers_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeMembers_Request) ProtoMessage() {}

func (x *SchemeMembers_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeMembers_Request.ProtoReflect.Descriptor instead.
func (*SchemeMembers_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SchemeMembers_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *SchemeMembers_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *SchemeMembers_Request) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *SchemeMembers_Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SchemeMembers_Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SchemeMembers_Request) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type SchemeMembers_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Total         int32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Members       []*SchemeMember_Response `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemeMembers_Response) Reset() {
	*x = SchemeMembers_Response{}
	mi := &file_member_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeMembers_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeMembers_Response) ProtoMessage() {}

func (x *SchemeMembers_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeMembers_Response.ProtoReflect.Descriptor instead.
func (*SchemeMembers_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{6, 1}
}

func (x *SchemeMembers_Response) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SchemeMembers_Response) GetMembers() []*SchemeMember_Response {
	if x != nil {
		return x.Members
	}
	return nil
}

type SchemeMember_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin        bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"-"`                        
	OwnerId        string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"-"`                         
	SchemeId       string                 `protobuf:"bytes,3,opt,name=scheme_id,json=schemeId,proto3" json:"-"`                      
	SchemeMemberId string                 `protobuf:"bytes,4,opt,name=scheme_member_id,json=schemeMemberId,proto3" json:"-"`  
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchemeMember_Request) Reset() {
	*x = SchemeMember_Request{}
	mi := &file_member_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeMember_Request) ProtoMessage() {}

func (x *SchemeMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeMember_Request.ProtoReflect.Descriptor instead.
func (*SchemeMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SchemeMember_Request) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *SchemeMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *SchemeMember_Request) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *SchemeMember_Request) GetSchemeMemberId() string {
	if x != nil {
		return x.SchemeMemberId
	}
	return ""
}

type SchemeMember_Response struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemeMemberId string                 `protobuf:"bytes,1,opt,name=scheme_member_id,json=schemeMemberId,proto3" json:"scheme_member_id,omitempty"`
	ProfileId      string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Alias          string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Surname        string                 `protobuf:"bytes,5,opt,name=surname,proto3" json:"surname,omitempty"`
	Email          string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Role           profile.Role           `protobuf:"varint,7,opt,name=role,proto3,enum=profile.Role" json:"role,omitempty"`
	Active         bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	Online         bool                   `protobuf:"varint,9,opt,name=online,proto3" json:"online,omitempty"`
	LockedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	ArchivedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchemeMember_Response) Reset() {
	*x = SchemeMember_Response{}
	mi := &file_member_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemeMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemeMember_Response) ProtoMessage() {}

func (x *SchemeMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemeMember_Response.ProtoReflect.Descriptor instead.
func (*SchemeMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{7, 1}
}

func (x *SchemeMember_Response) GetSchemeMemberId() string {
	if x != nil {
		return x.SchemeMemberId
	}
	return ""
}

func (x *SchemeMember_Response) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SchemeMember_Response) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SchemeMember_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemeMember_Response) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *SchemeMember_Response) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SchemeMember_Response) GetRole() profile.Role {
	if x != nil {
		return x.Role
	}
	return profile.Role(0)
}

func (x *SchemeMember_Response) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *SchemeMember_Response) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *SchemeMember_Response) GetLockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedAt
	}
	return nil
}

func (x *SchemeMember_Response) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *SchemeMember_Response) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SchemeMember_Response) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddSchemeMember_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"-"`     
	SchemeId      string                 `protobuf:"bytes,2,opt,name=scheme_id,json=schemeId,proto3" json:"-"`  
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSchemeMember_Request) Reset() {
	*x = AddSchemeMember_Request{}
	mi := &file_member_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSchemeMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSchemeMember_Request) ProtoMessage() {}

func (x *AddSchemeMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSchemeMember_Request.ProtoReflect.Descriptor instead.
func (*AddSchemeMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{8, 0}
}

func (x *AddSchemeMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AddSchemeMember_Request) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *AddSchemeMember_Request) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *AddSchemeMember_Request) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type AddSchemeMember_Response struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemeMemberId string                 `protobuf:"bytes,1,opt,name=scheme_member_id,json=schemeMemberId,proto3" json:"scheme_member_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddSchemeMember_Response) Reset() {
	*x = AddSchemeMember_Response{}
	mi := &file_member_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSchemeMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSchemeMember_Response) ProtoMessage() {}

func (x *AddSchemeMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSchemeMember_Response.ProtoReflect.Descriptor instead.
func (*AddSchemeMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{8, 1}
}

func (x *AddSchemeMember_Response) GetSchemeMemberId() string {
	if x != nil {
		return x.SchemeMemberId
	}
	return ""
}

type UpdateSchemeMember_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"-"`                         
	SchemeId       string                 `protobuf:"bytes,2,opt,name=scheme_id,json=schemeId,proto3" json:"-"`                      
	SchemeMemberId string                 `protobuf:"bytes,3,opt,name=scheme_member_id,json=schemeMemberId,proto3" json:"-"`  
	// Types that are valid to be assigned to Setting:
	//
	//	*UpdateSchemeMember_Request_Active
	//	*UpdateSchemeMember_Request_Online
	Setting       isUpdateSchemeMember_Request_Setting `protobuf_oneof:"setting"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemeMember_Request) Reset() {
	*x = UpdateSchemeMember_Request{}
	mi := &file_member_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemeMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemeMember_Request) ProtoMessage() {}

func (x *UpdateSchemeMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemeMember_Request.ProtoReflect.Descriptor instead.
func (*UpdateSchemeMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateSchemeMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UpdateSchemeMember_Request) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *UpdateSchemeMember_Request) GetSchemeMemberId() string {
	if x != nil {
		return x.SchemeMemberId
	}
	return ""
}

func (x *UpdateSchemeMember_Request) GetSetting() isUpdateSchemeMember_Request_Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *UpdateSchemeMember_Request) GetActive() bool {
	if x != nil {
		if x, ok := x.Setting.(*UpdateSchemeMember_Request_Active); ok {
			return x.Active
		}
	}
	return false
}

func (x *UpdateSchemeMember_Request) GetOnline() bool {
	if x != nil {
		if x, ok := x.Setting.(*UpdateSchemeMember_Request_Online); ok {
			return x.Online
		}
	}
	return false
}

type isUpdateSchemeMember_Request_Setting interface {
	isUpdateSchemeMember_Request_Setting()
}

type UpdateSchemeMember_Request_Active struct {
	Active bool `protobuf:"varint,4,opt,name=active,proto3,oneof"`
}

type UpdateSchemeMember_Request_Online struct {
	Online bool `protobuf:"varint,5,opt,name=online,proto3,oneof"`
}

func (*UpdateSchemeMember_Request_Active) isUpdateSchemeMember_Request_Setting() {}

func (*UpdateSchemeMember_Request_Online) isUpdateSchemeMember_Request_Setting() {}

type UpdateSchemeMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemeMember_Response) Reset() {
	*x = UpdateSchemeMember_Response{}
	mi := &file_member_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemeMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemeMember_Response) ProtoMessage() {}

func (x *UpdateSchemeMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemeMember_Response.ProtoReflect.Descriptor instead.
func (*UpdateSchemeMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{9, 1}
}

type DeleteSchemeMember_Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"-"`     
	SchemeId       string                 `protobuf:"bytes,2,opt,name=scheme_id,json=schemeId,proto3" json:"-"`  
	SchemeMemberId string                 `protobuf:"bytes,3,opt,name=scheme_member_id,json=schemeMemberId,proto3" json:"scheme_member_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSchemeMember_Request) Reset() {
	*x = DeleteSchemeMember_Request{}
	mi := &file_member_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemeMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemeMember_Request) ProtoMessage() {}

func (x *DeleteSchemeMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemeMember_Request.ProtoReflect.Descriptor instead.
func (*DeleteSchemeMember_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DeleteSchemeMember_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DeleteSchemeMember_Request) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *DeleteSchemeMember_Request) GetSchemeMemberId() string {
	if x != nil {
		return x.SchemeMemberId
	}
	return ""
}

type DeleteSchemeMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemeMember_Response) Reset() {
	*x = DeleteSchemeMember_Response{}
	mi := &file_member_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemeMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemeMember_Response) ProtoMessage() {}

func (x *DeleteSchemeMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemeMember_Response.ProtoReflect.Descriptor instead.
func (*DeleteSchemeMember_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{10, 1}
}

type MembersWithoutScheme_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"-"`     
	SchemeId      string                 `protobuf:"bytes,2,opt,name=scheme_id,json=schemeId,proto3" json:"-"`  
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"-"`  
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersWithoutScheme_Request) Reset() {
	*x = MembersWithoutScheme_Request{}
	mi := &file_member_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersWithoutScheme_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersWithoutScheme_Request) ProtoMessage() {}

func (x *MembersWithoutScheme_Request) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersWithoutScheme_Request.ProtoReflect.Descriptor instead.
func (*MembersWithoutScheme_Request) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{11, 0}
}

func (x *MembersWithoutScheme_Request) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MembersWithoutScheme_Request) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

func (x *MembersWithoutScheme_Request) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *MembersWithoutScheme_Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MembersWithoutScheme_Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MembersWithoutScheme_Request) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type MembersWithoutScheme_Response struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Total         int32                          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Members       []*MembersWithoutScheme_Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersWithoutScheme_Response) Reset() {
	*x = MembersWithoutScheme_Response{}
	mi := &file_member_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersWithoutScheme_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersWithoutScheme_Response) ProtoMessage() {}

func (x *MembersWithoutScheme_Response) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersWithoutScheme_Response.ProtoReflect.Descriptor instead.
func (*MembersWithoutScheme_Response) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{11, 1}
}

func (x *MembersWithoutScheme_Response) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MembersWithoutScheme_Response) GetMembers() []*MembersWithoutScheme_Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type MembersWithoutScheme_Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,5,opt,name=surname,proto3" json:"surname,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Role          profile.Role           `protobuf:"varint,7,opt,name=role,proto3,enum=profile.Role" json:"role,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	Online        bool                   `protobuf:"varint,9,opt,name=online,proto3" json:"online,omitempty"`
	LockedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersWithoutScheme_Member) Reset() {
	*x = MembersWithoutScheme_Member{}
	mi := &file_member_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersWithoutScheme_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersWithoutScheme_Member) ProtoMessage() {}

func (x *MembersWithoutScheme_Member) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersWithoutScheme_Member.ProtoReflect.Descriptor instead.
func (*MembersWithoutScheme_Member) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{11, 2}
}

func (x *MembersWithoutScheme_Member) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *MembersWithoutScheme_Member) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *MembersWithoutScheme_Member) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *MembersWithoutScheme_Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MembersWithoutScheme_Member) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *MembersWithoutScheme_Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MembersWithoutScheme_Member) GetRole() profile.Role {
	if x != nil {
		return x.Role
	}
	return profile.Role(0)
}

func (x *MembersWithoutScheme_Member) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MembersWithoutScheme_Member) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *MembersWithoutScheme_Member) GetLockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedAt
	}
	return nil
}

func (x *MembersWithoutScheme_Member) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *MembersWithoutScheme_Member) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MembersWithoutScheme_Member) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_member_proto protoreflect.FileDescriptor

const file_member_proto_rawDesc = "" +
	"\n" +
	"\fmember.proto\x12\x06member\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a0pkg/utils/protoutils/ghoster/proto/ghoster.proto\x1a1internal/core/profile/proto/profile/profile.proto\"\xae\x02\n" +
	"\x0eProjectMembers\x1a\xbf\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12&\n" +
	"\bowner_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12*\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprojectId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x1aZ\n" +
	"\bResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x128\n" +
	"\amembers\x18\x02 \x03(\v2\x1e.member.ProjectMember.ResponseR\amembers\"\xa1\x06\n" +
	"\rProjectMember\x1a\xa2\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12&\n" +
	"\bowner_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12*\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprojectId\x12(\n" +
	"\tmember_id\x18\x04 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bmemberId\x1a\xea\x04\n" +
	"\bResponse\x12\x1f\n" +
	"\bowner_id\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\aownerId\x12#\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\townerName\x12#\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tB\x04\x88\xb5\x18\x01R\tprojectId\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x1b\n" +
	"\tmember_id\x18\x05 \x01(\tR\bmemberId\x12#\n" +
	"\n" +
	"profile_id\x18\x06 \x01(\tB\x04\x88\xb5\x18\x01R\tprofileId\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12'\n" +
	"\x04role\x18\b \x01(\x0e2\r.profile.RoleB\x04\x88\xb5\x18\x01R\x04role\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12\x16\n" +
	"\x06online\x18\n" +
	" \x01(\bR\x06online\x12#\n" +
	"\rschemes_count\x18\v \x01(\x05R\fschemesCount\x12=\n" +
	"\tlocked_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\blockedAt\x12A\n" +
	"\varchived_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\n" +
	"archivedAt\x12?\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8e\x02\n" +
	"\x10AddProjectMember\x1a\xd0\x01\n" +
	"\aRequest\x12&\n" +
	"\bowner_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12*\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprojectId\x12*\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprofileId\x12-\n" +
	"\x04role\x18\x04 \x01(\x0e2\r.profile.RoleB\n" +
	"\xbaH\a\x82\x01\x04\x18\x01\x18\x02R\x04role\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x1a'\n" +
	"\bResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\xa3\x02\n" +
	"\x13UpdateProjectMember\x1a\xff\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12&\n" +
	"\bowner_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12*\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprojectId\x12(\n" +
	"\tmember_id\x18\x04 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bmemberId\x12/\n" +
	"\x04role\x18\x05 \x01(\x0e2\r.profile.RoleB\n" +
	"\xbaH\a\x82\x01\x04\x18\x01\x18\x02H\x00R\x04role\x12\x18\n" +
	"\x06active\x18\x06 \x01(\bH\x00R\x06activeB\x10\n" +
	"\asetting\x12\x05\xbaH\x02\b\x01\x1a\n" +
	"\n" +
	"\bResponse\"\xab\x01\n" +
	"\x13DeleteProjectMember\x1a\x87\x01\n" +
	"\aRequest\x12&\n" +
	"\bowner_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12*\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprojectId\x12(\n" +
	"\tmember_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bmemberId\x1a\n" +
	"\n" +
	"\bResponse\"\xa2\x03\n" +
	"\x16ProfilesWithoutProject\x1a\xad\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12*\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\tprojectId\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x1ad\n" +
	"\bResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12B\n" +
	"\bprofiles\x18\x02 \x03(\v2&.member.ProfilesWithoutProject.ProfileR\bprofiles\x1ar\n" +
	"\aProfile\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1a\n" +
	"\x05email\x18\x04 \x01(\tB\x04\x88\xb5\x18\x01R\x05email\"\xaa\x02\n" +
	"\rSchemeMembers\x1a\xbd\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12&\n" +
	"\bowner_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12(\n" +
	"\tscheme_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemeId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x1aY\n" +
	"\bResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x127\n" +
	"\amembers\x18\x02 \x03(\v2\x1d.member.SchemeMember.ResponseR\amembers\"\xd1\x05\n" +
	"\fSchemeMember\x1a\xad\x01\n" +
	"\aRequest\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\x12&\n" +
	"\bowner_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12(\n" +
	"\tscheme_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemeId\x125\n" +
	"\x10scheme_member_id\x18\x04 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eschemeMemberId\x1a\x90\x04\n" +
	"\bResponse\x12(\n" +
	"\x10scheme_member_id\x18\x01 \x01(\tR\x0eschemeMemberId\x12#\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\tprofileId\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x05 \x01(\tR\asurname\x12\x1a\n" +
	"\x05email\x18\x06 \x01(\tB\x04\x88\xb5\x18\x01R\x05email\x12'\n" +
	"\x04role\x18\a \x01(\x0e2\r.profile.RoleB\x04\x88\xb5\x18\x01R\x04role\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12\x16\n" +
	"\x06online\x18\t \x01(\bR\x06online\x12=\n" +
	"\tlocked_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\blockedAt\x12A\n" +
	"\varchived_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\n" +
	"archivedAt\x12?\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe7\x01\n" +
	"\x0fAddSchemeMember\x1a\x9d\x01\n" +
	"\aRequest\x12&\n" +
	"\bowner_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12(\n" +
	"\tscheme_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemeId\x12(\n" +
	"\tmember_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bmemberId\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x1a4\n" +
	"\bResponse\x12(\n" +
	"\x10scheme_member_id\x18\x01 \x01(\tR\x0eschemeMemberId\"\xfb\x01\n" +
	"\x12UpdateSchemeMember\x1a\xd8\x01\n" +
	"\aRequest\x12&\n" +
	"\bowner_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12(\n" +
	"\tscheme_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemeId\x125\n" +
	"\x10scheme_member_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eschemeMemberId\x12\x18\n" +
	"\x06active\x18\x04 \x01(\bH\x00R\x06active\x12\x18\n" +
	"\x06online\x18\x05 \x01(\bH\x00R\x06onlineB\x10\n" +
	"\asetting\x12\x05\xbaH\x02\b\x01\x1a\n" +
	"\n" +
	"\bResponse\"\xb5\x01\n" +
	"\x12DeleteSchemeMember\x1a\x92\x01\n" +
	"\aRequest\x12&\n" +
	"\bowner_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12(\n" +
	"\tscheme_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemeId\x125\n" +
	"\x10scheme_member_id\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0eschemeMemberId\x1a\n" +
	"\n" +
	"\bResponse\"\xb6\x06\n" +
	"\x14MembersWithoutScheme\x1a\xb8\x01\n" +
	"\aRequest\x12&\n" +
	"\bowner_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12(\n" +
	"\tscheme_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bschemeId\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x1a_\n" +
	"\bResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12=\n" +
	"\amembers\x18\x02 \x03(\v2#.member.MembersWithoutScheme.MemberR\amembers\x1a\x81\x04\n" +
	"\x06Member\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12#\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\tprofileId\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x05 \x01(\tR\asurname\x12\x1a\n" +
	"\x05email\x18\x06 \x01(\tB\x04\x88\xb5\x18\x01R\x05email\x12'\n" +
	"\x04role\x18\a \x01(\x0e2\r.profile.RoleB\x04\x88\xb5\x18\x01R\x04role\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12\x16\n" +
	"\x06online\x18\t \x01(\bR\x06online\x12=\n" +
	"\tlocked_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\blockedAt\x12A\n" +
	"\varchived_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\n" +
	"archivedAt\x12?\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x04\x88\xb5\x18\x01R\tupdatedAt\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*8\n" +
	"\fInviteStatus\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\b\n" +
	"\x04send\x10\x01\x12\r\n" +
	"\tactivated\x10\x022\xe9\b\n" +
	"\x0eMemberHandlers\x12S\n" +
	"\x0eProjectMembers\x12\x1e.member.ProjectMembers.Request\x1a\x1f.member.ProjectMembers.Response\"\x00\x12P\n" +
	"\rProjectMember\x12\x1d.member.ProjectMember.Request\x1a\x1e.member.ProjectMember.Response\"\x00\x12Y\n" +
	"\x10AddProjectMember\x12 .member.AddProjectMember.Request\x1a!.member.AddProjectMember.Response\"\x00\x12b\n" +
	"\x13UpdateProjectMember\x12#.member.UpdateProjectMember.Request\x1a$.member.UpdateProjectMember.Response\"\x00\x12b\n" +
	"\x13DeleteProjectMember\x12#.member.DeleteProjectMember.Request\x1a$.member.DeleteProjectMember.Response\"\x00\x12k\n" +
	"\x16ProfilesWithoutProject\x12&.member.ProfilesWithoutProject.Request\x1a'.member.ProfilesWithoutProject.Response\"\x00\x12P\n" +
	"\rSchemeMembers\x12\x1d.member.SchemeMembers.Request\x1a\x1e.member.SchemeMembers.Response\"\x00\x12M\n" +
	"\fSchemeMember\x12\x1c.member.SchemeMember.Request\x1a\x1d.member.SchemeMember.Response\"\x00\x12V\n" +
	"\x0fAddSchemeMember\x12\x1f.member.AddSchemeMember.Request\x1a .member.AddSchemeMember.Response\"\x00\x12_\n" +
	"\x12UpdateSchemeMember\x12\".member.UpdateSchemeMember.Request\x1a#.member.UpdateSchemeMember.Response\"\x00\x12_\n" +
	"\x12DeleteSchemeMember\x12\".member.DeleteSchemeMember.Request\x1a#.member.DeleteSchemeMember.Response\"\x00\x12e\n" +
	"\x14MembersWithoutScheme\x12$.member.MembersWithoutScheme.Request\x1a%.member.MembersWithoutScheme.Response\"\x00B<Z:github.com/werbot/werbot/internal/core/member/proto/memberb\x06proto3"

var (
	file_member_proto_rawDescOnce sync.Once
	file_member_proto_rawDescData []byte
)

func file_member_proto_rawDescGZIP() []byte {
	file_member_proto_rawDescOnce.Do(func() {
		file_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)))
	})
	return file_member_proto_rawDescData
}

var file_member_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_member_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_member_proto_goTypes = []any{
	(InviteStatus)(0),                       // 0: member.InviteStatus
	(*ProjectMembers)(nil),                  // 1: member.ProjectMembers
	(*ProjectMember)(nil),                   // 2: member.ProjectMember
	(*AddProjectMember)(nil),                // 3: member.AddProjectMember
	(*UpdateProjectMember)(nil),             // 4: member.UpdateProjectMember
	(*DeleteProjectMember)(nil),             // 5: member.DeleteProjectMember
	(*ProfilesWithoutProject)(nil),          // 6: member.ProfilesWithoutProject
	(*SchemeMembers)(nil),                   // 7: member.SchemeMembers
	(*SchemeMember)(nil),                    // 8: member.SchemeMember
	(*AddSchemeMember)(nil),                 // 9: member.AddSchemeMember
	(*UpdateSchemeMember)(nil),              // 10: member.UpdateSchemeMember
	(*DeleteSchemeMember)(nil),              // 11: member.DeleteSchemeMember
	(*MembersWithoutScheme)(nil),            // 12: member.MembersWithoutScheme
	(*ProjectMembers_Request)(nil),          // 13: member.ProjectMembers.Request
	(*ProjectMembers_Response)(nil),         // 14: member.ProjectMembers.Response
	(*ProjectMember_Request)(nil),           // 15: member.ProjectMember.Request
	(*ProjectMember_Response)(nil),          // 16: member.ProjectMember.Response
	(*AddProjectMember_Request)(nil),        // 17: member.AddProjectMember.Request
	(*AddProjectMember_Response)(nil),       // 18: member.AddProjectMember.Response
	(*UpdateProjectMember_Request)(nil),     // 19: member.UpdateProjectMember.Request
	(*UpdateProjectMember_Response)(nil),    // 20: member.UpdateProjectMember.Response
	(*DeleteProjectMember_Request)(nil),     // 21: member.DeleteProjectMember.Request
	(*DeleteProjectMember_Response)(nil),    // 22: member.DeleteProjectMember.Response
	(*ProfilesWithoutProject_Request)(nil),  // 23: member.ProfilesWithoutProject.Request
	(*ProfilesWithoutProject_Response)(nil), // 24: member.ProfilesWithoutProject.Response
	(*ProfilesWithoutProject_Profile)(nil),  // 25: member.ProfilesWithoutProject.Profile
	(*SchemeMembers_Request)(nil),           // 26: member.SchemeMembers.Request
	(*SchemeMembers_Response)(nil),          // 27: member.SchemeMembers.Response
	(*SchemeMember_Request)(nil),            // 28: member.SchemeMember.Request
	(*SchemeMember_Response)(nil),           // 29: member.SchemeMember.Response
	(*AddSchemeMember_Request)(nil),         // 30: member.AddSchemeMember.Request
	(*AddSchemeMember_Response)(nil),        // 31: member.AddSchemeMember.Response
	(*UpdateSchemeMember_Request)(nil),      // 32: member.UpdateSchemeMember.Request
	(*UpdateSchemeMember_Response)(nil),     // 33: member.UpdateSchemeMember.Response
	(*DeleteSchemeMember_Request)(nil),      // 34: member.DeleteSchemeMember.Request
	(*DeleteSchemeMember_Response)(nil),     // 35: member.DeleteSchemeMember.Response
	(*MembersWithoutScheme_Request)(nil),    // 36: member.MembersWithoutScheme.Request
	(*MembersWithoutScheme_Response)(nil),   // 37: member.MembersWithoutScheme.Response
	(*MembersWithoutScheme_Member)(nil),     // 38: member.MembersWithoutScheme.Member
	(profile.Role)(0),                       // 39: profile.Role
	(*timestamppb.Timestamp)(nil),           // 40: google.protobuf.Timestamp
}
var file_member_proto_depIdxs = []int32{
	16, // 0: member.ProjectMembers.Response.members:type_name -> member.ProjectMember.Response
	39, // 1: member.ProjectMember.Response.role:type_name -> profile.Role
	40, // 2: member.ProjectMember.Response.locked_at:type_name -> google.protobuf.Timestamp
	40, // 3: member.ProjectMember.Response.archived_at:type_name -> google.protobuf.Timestamp
	40, // 4: member.ProjectMember.Response.updated_at:type_name -> google.protobuf.Timestamp
	40, // 5: member.ProjectMember.Response.created_at:type_name -> google.protobuf.Timestamp
	39, // 6: member.AddProjectMember.Request.role:type_name -> profile.Role
	39, // 7: member.UpdateProjectMember.Request.role:type_name -> profile.Role
	25, // 8: member.ProfilesWithoutProject.Response.profiles:type_name -> member.ProfilesWithoutProject.Profile
	29, // 9: member.SchemeMembers.Response.members:type_name -> member.SchemeMember.Response
	39, // 10: member.SchemeMember.Response.role:type_name -> profile.Role
	40, // 11: member.SchemeMember.Response.locked_at:type_name -> google.protobuf.Timestamp
	40, // 12: member.SchemeMember.Response.archived_at:type_name -> google.protobuf.Timestamp
	40, // 13: member.SchemeMember.Response.updated_at:type_name -> google.protobuf.Timestamp
	40, // 14: member.SchemeMember.Response.created_at:type_name -> google.protobuf.Timestamp
	38, // 15: member.MembersWithoutScheme.Response.members:type_name -> member.MembersWithoutScheme.Member
	39, // 16: member.MembersWithoutScheme.Member.role:type_name -> profile.Role
	40, // 17: member.MembersWithoutScheme.Member.locked_at:type_name -> google.protobuf.Timestamp
	40, // 18: member.MembersWithoutScheme.Member.archived_at:type_name -> google.protobuf.Timestamp
	40, // 19: member.MembersWithoutScheme.Member.updated_at:type_name -> google.protobuf.Timestamp
	40, // 20: member.MembersWithoutScheme.Member.created_at:type_name -> google.protobuf.Timestamp
	13, // 21: member.MemberHandlers.ProjectMembers:input_type -> member.ProjectMembers.Request
	15, // 22: member.MemberHandlers.ProjectMember:input_type -> member.ProjectMember.Request
	17, // 23: member.MemberHandlers.AddProjectMember:input_type -> member.AddProjectMember.Request
	19, // 24: member.MemberHandlers.UpdateProjectMember:input_type -> member.UpdateProjectMember.Request
	21, // 25: member.MemberHandlers.DeleteProjectMember:input_type -> member.DeleteProjectMember.Request
	23, // 26: member.MemberHandlers.ProfilesWithoutProject:input_type -> member.ProfilesWithoutProject.Request
	26, // 27: member.MemberHandlers.SchemeMembers:input_type -> member.SchemeMembers.Request
	28, // 28: member.MemberHandlers.SchemeMember:input_type -> member.SchemeMember.Request
	30, // 29: member.MemberHandlers.AddSchemeMember:input_type -> member.AddSchemeMember.Request
	32, // 30: member.MemberHandlers.UpdateSchemeMember:input_type -> member.UpdateSchemeMember.Request
	34, // 31: member.MemberHandlers.DeleteSchemeMember:input_type -> member.DeleteSchemeMember.Request
	36, // 32: member.MemberHandlers.MembersWithoutScheme:input_type -> member.MembersWithoutScheme.Request
	14, // 33: member.MemberHandlers.ProjectMembers:output_type -> member.ProjectMembers.Response
	16, // 34: member.MemberHandlers.ProjectMember:output_type -> member.ProjectMember.Response
	18, // 35: member.MemberHandlers.AddProjectMember:output_type -> member.AddProjectMember.Response
	20, // 36: member.MemberHandlers.UpdateProjectMember:output_type -> member.UpdateProjectMember.Response
	22, // 37: member.MemberHandlers.DeleteProjectMember:output_type -> member.DeleteProjectMember.Response
	24, // 38: member.MemberHandlers.ProfilesWithoutProject:output_type -> member.ProfilesWithoutProject.Response
	27, // 39: member.MemberHandlers.SchemeMembers:output_type -> member.SchemeMembers.Response
	29, // 40: member.MemberHandlers.SchemeMember:output_type -> member.SchemeMember.Response
	31, // 41: member.MemberHandlers.AddSchemeMember:output_type -> member.AddSchemeMember.Response
	33, // 42: member.MemberHandlers.UpdateSchemeMember:output_type -> member.UpdateSchemeMember.Response
	35, // 43: member.MemberHandlers.DeleteSchemeMember:output_type -> member.DeleteSchemeMember.Response
	37, // 44: member.MemberHandlers.MembersWithoutScheme:output_type -> member.MembersWithoutScheme.Response
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_member_proto_init() }
func file_member_proto_init() {
	if File_member_proto != nil {
		return
	}
	file_member_proto_msgTypes[18].OneofWrappers = []any{
		(*UpdateProjectMember_Request_Role)(nil),
		(*UpdateProjectMember_Request_Active)(nil),
	}
	file_member_proto_msgTypes[31].OneofWrappers = []any{
		(*UpdateSchemeMember_Request_Active)(nil),
		(*UpdateSchemeMember_Request_Online)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_proto_goTypes,
		DependencyIndexes: file_member_proto_depIdxs,
		EnumInfos:         file_member_proto_enumTypes,
		MessageInfos:      file_member_proto_msgTypes,
	}.Build()
	File_member_proto = out.File
	file_member_proto_goTypes = nil
	file_member_proto_depIdxs = nil
}
