#!/usr/bin/env bash

set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/helper

support_arch

case "$OS" in
Darwin)
  brew install protobuf protoc-gen-go protoc-gen-go-grpc goose golangci-lint yq
  ;;
Linux)
  if ! [ -d ${ROOT_PATH}/.vscode/tmp ]; then
    mkdir ${ROOT_PATH}/.vscode/tmp
  fi

  print_header "Install/Update golangci-lint"
  GOLINTER_LATEST=$(get_latest_release "golangci/golangci-lint")
  wget "https://github.com/golangci/golangci-lint/releases/download/${GOLINTER_LATEST}/golangci-lint-${GOLINTER_LATEST#*v}-linux-amd64.tar.gz" -4 -q -O ${ROOT_PATH}/.vscode/tmp/golangci-lint.tar.gz
  tar --no-same-owner -xzf ${ROOT_PATH}/.vscode/tmp/golangci-lint.tar.gz -C ${ROOT_PATH}/.vscode/tmp
  install "${ROOT_PATH}/.vscode/tmp/golangci-lint-${GOLINTER_LATEST#*v}-linux-amd64/golangci-lint" "$HOME/.local/bin"
  print_answer "SUCCESS" green

  print_header "Install/Update protobuf"
  PROTOS_LATEST=$(get_latest_release "protocolbuffers/protobuf")
  wget "https://github.com/protocolbuffers/protobuf/releases/download/${PROTOS_LATEST}/protoc-${PROTOS_LATEST#*v}-linux-x86_64.zip" -4 -q -O ${ROOT_PATH}/.vscode/tmp/protoc.zip
  unzip -o ${ROOT_PATH}/.vscode/tmp/protoc.zip -d $HOME/.local >/dev/null 2>&1
  print_answer "SUCCESS" green

  print_header "Install/Update protoc-gen-validate"
  VALIDATE_LATEST=$(get_latest_release "bufbuild/protoc-gen-validate")
  wget "https://github.com/bufbuild/protoc-gen-validate/releases/download/${VALIDATE_LATEST}/protoc-gen-validate_${VALIDATE_LATEST#*v}_linux_amd64.tar.gz" -4 -q -O ${ROOT_PATH}/.vscode/tmp/protoc-gen-validate.tar.gz
  tar --no-same-owner -xzf ${ROOT_PATH}/.vscode/tmp/protoc-gen-validate.tar.gz -C ${ROOT_PATH}/.vscode/tmp
  install "${ROOT_PATH}/.vscode/tmp/protoc-gen-validate" "$HOME/.local/bin"
  install "${ROOT_PATH}/.vscode/tmp/protoc-gen-validate-go" "$HOME/.local/bin"
  if ! [ -d ${ROOT_PATH}/.vscode/tmp/protoc-gen-validate-git ]; then
    mkdir ${ROOT_PATH}/.vscode/tmp/protoc-gen-validate-git
    git clone https://github.com/bufbuild/protoc-gen-validate.git ${ROOT_PATH}/.vscode/tmp/protoc-gen-validate-git >/dev/null 2>&1
  fi
  rm -rf $HOME/.local/include/validate
  cp -a ${ROOT_PATH}/.vscode/tmp/protoc-gen-validate-git/validate $HOME/.local/include
  print_answer "SUCCESS" green

  print_header "Install/Update protoc-gen-go"
  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
  print_answer "SUCCESS" green

  print_header "Install/Update protoc-gen-go-grpc"
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
  print_answer "SUCCESS" green

  print_header "Install/Update protoc-go-inject-tag"
  go install github.com/favadi/protoc-go-inject-tag@latest
  print_answer "SUCCESS" green

  print_header "Install/Update goose"
  go install github.com/pressly/goose/v3/cmd/goose@latest
  print_answer "SUCCESS" green

  print_header "Install/Update yq"
  wget "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -4 -q -O ${ROOT_PATH}/.vscode/tmp/yq
  install "${ROOT_PATH}/.vscode/tmp/yq" "$HOME/.local/bin"
  print_answer "SUCCESS" green

  rm -rf ${ROOT_PATH}/.vscode/tmp

  source ~/.profile
  ;;
*)
  print_header "Install/Update mods"
  print_answer "ERROR" red
  echo "Unsupported OS: $OS"
  exit
  ;;
esac
