// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile_Section int32

const (
	Profile_section_unspecified Profile_Section = 0
	Profile_profile             Profile_Section = 1
	Profile_setting             Profile_Section = 2
	Profile_password            Profile_Section = 3
	Profile_ssh_key             Profile_Section = 4
	Profile_license             Profile_Section = 5
	Profile_project             Profile_Section = 6
)

// Enum value maps for Profile_Section.
var (
	Profile_Section_name = map[int32]string{
		0: "section_unspecified",
		1: "profile",
		2: "setting",
		3: "password",
		4: "ssh_key",
		5: "license",
		6: "project",
	}
	Profile_Section_value = map[string]int32{
		"section_unspecified": 0,
		"profile":             1,
		"setting":             2,
		"password":            3,
		"ssh_key":             4,
		"license":             5,
		"project":             6,
	}
)

func (x Profile_Section) Enum() *Profile_Section {
	p := new(Profile_Section)
	*p = x
	return p
}

func (x Profile_Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Profile_Section) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Profile_Section) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Profile_Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Profile_Section.Descriptor instead.
func (Profile_Section) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1, 0}
}

type Project_Section int32

const (
	Project_section_unspecified Project_Section = 0
	Project_project             Project_Section = 1
	Project_setting             Project_Section = 2
	Project_member              Project_Section = 3
	Project_team                Project_Section = 4
	Project_server              Project_Section = 10
	Project_database            Project_Section = 11
	Project_application         Project_Section = 12
	Project_desktop             Project_Section = 13
	Project_container           Project_Section = 14
	Project_cloud               Project_Section = 15
)

// Enum value maps for Project_Section.
var (
	Project_Section_name = map[int32]string{
		0:  "section_unspecified",
		1:  "project",
		2:  "setting",
		3:  "member",
		4:  "team",
		10: "server",
		11: "database",
		12: "application",
		13: "desktop",
		14: "container",
		15: "cloud",
	}
	Project_Section_value = map[string]int32{
		"section_unspecified": 0,
		"project":             1,
		"setting":             2,
		"member":              3,
		"team":                4,
		"server":              10,
		"database":            11,
		"application":         12,
		"desktop":             13,
		"container":           14,
		"cloud":               15,
	}
)

func (x Project_Section) Enum() *Project_Section {
	p := new(Project_Section)
	*p = x
	return p
}

func (x Project_Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Project_Section) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (Project_Section) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x Project_Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Project_Section.Descriptor instead.
func (Project_Section) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2, 0}
}

type Scheme_Section int32

const (
	Scheme_section_unspecified Scheme_Section = 0
	Scheme_scheme              Scheme_Section = 1
	Scheme_member              Scheme_Section = 2
	Scheme_activity            Scheme_Section = 3
	Scheme_firewall            Scheme_Section = 4
	Scheme_setting             Scheme_Section = 5
)

// Enum value maps for Scheme_Section.
var (
	Scheme_Section_name = map[int32]string{
		0: "section_unspecified",
		1: "scheme",
		2: "member",
		3: "activity",
		4: "firewall",
		5: "setting",
	}
	Scheme_Section_value = map[string]int32{
		"section_unspecified": 0,
		"scheme":              1,
		"member":              2,
		"activity":            3,
		"firewall":            4,
		"setting":             5,
	}
)

func (x Scheme_Section) Enum() *Scheme_Section {
	p := new(Scheme_Section)
	*p = x
	return p
}

func (x Scheme_Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scheme_Section) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (Scheme_Section) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x Scheme_Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scheme_Section.Descriptor instead.
func (Scheme_Section) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3, 0}
}

// session data
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// section profile
type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Section       Profile_Section        `protobuf:"varint,2,opt,name=section,proto3,enum=eventmessage.Profile_Section" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetSection() Profile_Section {
	if x != nil {
		return x.Section
	}
	return Profile_section_unspecified
}

// section project
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Section       Project_Section        `protobuf:"varint,2,opt,name=section,proto3,enum=eventmessage.Project_Section" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetSection() Project_Section {
	if x != nil {
		return x.Section
	}
	return Project_section_unspecified
}

// section scheme
type Scheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Section       Scheme_Section         `protobuf:"varint,2,opt,name=section,proto3,enum=eventmessage.Scheme_Section" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scheme) Reset() {
	*x = Scheme{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheme) ProtoMessage() {}

func (x *Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheme.ProtoReflect.Descriptor instead.
func (*Scheme) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *Scheme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scheme) GetSection() Scheme_Section {
	if x != nil {
		return x.Section
	}
	return Scheme_section_unspecified
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\feventmessage\x1a\x1bbuf/validate/validate.proto\"[\n" +
	"\aSession\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x17\n" +
	"\x02ip\x18\x03 \x01(\tB\a\xbaH\x04r\x02p\x01R\x02ip\"\xdf\x01\n" +
	"\aProfile\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12D\n" +
	"\asection\x18\x02 \x01(\x0e2\x1d.eventmessage.Profile.SectionB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\asection\"q\n" +
	"\aSection\x12\x17\n" +
	"\x13section_unspecified\x10\x00\x12\v\n" +
	"\aprofile\x10\x01\x12\v\n" +
	"\asetting\x10\x02\x12\f\n" +
	"\bpassword\x10\x03\x12\v\n" +
	"\assh_key\x10\x04\x12\v\n" +
	"\alicense\x10\x05\x12\v\n" +
	"\aproject\x10\x06\"\x93\x02\n" +
	"\aProject\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12D\n" +
	"\asection\x18\x02 \x01(\x0e2\x1d.eventmessage.Project.SectionB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\asection\"\xa4\x01\n" +
	"\aSection\x12\x17\n" +
	"\x13section_unspecified\x10\x00\x12\v\n" +
	"\aproject\x10\x01\x12\v\n" +
	"\asetting\x10\x02\x12\n" +
	"\n" +
	"\x06member\x10\x03\x12\b\n" +
	"\x04team\x10\x04\x12\n" +
	"\n" +
	"\x06server\x10\n" +
	"\x12\f\n" +
	"\bdatabase\x10\v\x12\x0f\n" +
	"\vapplication\x10\f\x12\v\n" +
	"\adesktop\x10\r\x12\r\n" +
	"\tcontainer\x10\x0e\x12\t\n" +
	"\x05cloud\x10\x0f\"\xcf\x01\n" +
	"\x06Scheme\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12C\n" +
	"\asection\x18\x02 \x01(\x0e2\x1c.eventmessage.Scheme.SectionB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\asection\"c\n" +
	"\aSection\x12\x17\n" +
	"\x13section_unspecified\x10\x00\x12\n" +
	"\n" +
	"\x06scheme\x10\x01\x12\n" +
	"\n" +
	"\x06member\x10\x02\x12\f\n" +
	"\bactivity\x10\x03\x12\f\n" +
	"\bfirewall\x10\x04\x12\v\n" +
	"\asetting\x10\x05B<Z:github.com/werbot/werbot/internal/core/event/proto/messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(Profile_Section)(0), // 0: eventmessage.Profile.Section
	(Project_Section)(0), // 1: eventmessage.Project.Section
	(Scheme_Section)(0),  // 2: eventmessage.Scheme.Section
	(*Session)(nil),      // 3: eventmessage.Session
	(*Profile)(nil),      // 4: eventmessage.Profile
	(*Project)(nil),      // 5: eventmessage.Project
	(*Scheme)(nil),       // 6: eventmessage.Scheme
}
var file_message_proto_depIdxs = []int32{
	0, // 0: eventmessage.Profile.section:type_name -> eventmessage.Profile.Section
	1, // 1: eventmessage.Project.section:type_name -> eventmessage.Project.Section
	2, // 2: eventmessage.Scheme.section:type_name -> eventmessage.Scheme.Section
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
