server:
  http_listen_port: 9080
  grpc_listen_port: 0
  #log_level: "warn"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring.loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers

    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
            log:
      - json:
          expressions:
            level: level
            module: module
            message: message
            error: error
            user_name: userName
            user_address: userAddress
            user_id: userID
            uuid: UUID
            host_id: hostID
          source: log
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: ^(?P<image_name>([^|]+))\|(?P<container_name>([^|]+))$
          source: "tag"
      - labels:
          image_name:
          container_name:
          level:
          module:
          message:
          error:
          user_name:
          user_address:
          user_id:
          uuid:
          host_id:
      - match:
          selector: '{job="docker",container_name="",image_name=""}'
          action: drop
#      - match:
#          selector: '{container_name=~".*-avocado-.*"}'
#          stages:
#            - json:
#                expressions:
#                  level: level
#                  module: module
#                  message: message
#                source: log
#            - labels:
#                level:
#                module:
#                message:
