#!/usr/bin/env bash

#set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/_helper

arr_process=(__debug_bin vite)
for process in "${arr_process[@]}"; do
  if pkill -f "$process" >/dev/null; then
    print_header "Killing $process process"
    print_answer "SUCCESS" green
  fi
done

print_header "Remove old bin and dist files"
for entry in ${ROOT_PATH}/cmd/*/; do
  name=$(basename "${entry}")
  rm -rf ${ROOT_PATH}/cmd/${name}/__debug_bin*
done
rm -rf ${ROOT_PATH}/web/dist ${ROOT_PATH}/bin/* ${ROOT_PATH}/dist/
print_answer "SUCCESS" green

if [[ "$1" == 'docker' ]]; then
  print_header "Leaning garbage and inactive containers"
  docker system prune --all --volumes --force >/dev/null 2>&1
  docker image prune --filter "dangling=true" --force >/dev/null 2>&1
  print_answer "SUCCESS" green
fi

pids=$(pgrep -f "postgres.*9")
if [ -n "$pids" ]; then
  for process in $pids; do
    print_header "Killing $process process"
    if sudo kill "$process" >/dev/null; then # add sudo if need
      print_answer "SUCCESS" green
    else
      print_answer "ERROR" red
    fi
  done
fi
