#!/usr/bin/env bash

set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/_helper
source ${ROOT_PATH}/.env

CORE_DIR="${ROOT_PATH}/docker/core"
TMP_DIR="${ROOT_PATH}/.vscode/tmp"

mkdir -p "${CORE_DIR}"

print_header "Download GeoLite database"

if [ ! ${GEOLITE_LICENSE} ]; then
  print_answer "ERROR" red
  echo "GEOLITE_LICENSE no key "
  exit
fi

rm -rf ${CORE_DIR}/GeoLite2-Country.mmdb

mkdir -p ${TMP_DIR}
wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${GEOLITE_LICENSE}&suffix=tar.gz" -4 -q -O ${TMP_DIR}/country.tar.gz
tar -zxf ${TMP_DIR}/country.tar.gz -C ${TMP_DIR}
cp $(ls -d ${TMP_DIR}/*/ | head -n 1)*.mmdb ${CORE_DIR}/GeoLite2-Country.mmdb
rm -rf ${TMP_DIR}

print_answer "SUCCESS" green
